'use strict';
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
let personas=[],presets=[],personaPresets=[],scenes=[],settings={},models=[],draft=null,current=null,cid=null,abort=null,noticeTimer=null,rawStream='',recognition=null,previewTimer=null,busy=false;
const stateLabels={idle:'待命',listening:'聆聽中',thinking:'思考中',speaking:'說話中',error:'發生錯誤'};
async function api(path,options={}){const h={'X-Salesman-Local':'1',...options.headers};if(options.body&&!(options.body instanceof FormData))h['Content-Type']='application/json';const r=await fetch(path,{...options,headers:h});if(!r.ok){let d;try{d=await r.json()}catch{}const detail=d?.detail,msg=Array.isArray(detail)?detail.map(x=>String(x.msg||'').replace(/^Value error, /,'')).filter(Boolean).join('；'):detail;throw Error(typeof msg==='string'&&msg?msg:'操作失敗，請檢查輸入資料。')}return r.status===204?null:r.json()}
function notify(s){$('notice').textContent=s;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,6500)}
function state(s){$('stage').dataset.state=s;$('stateLabel').textContent=stateLabels[s]||s}
function setCue(stage,e='neutral',g='still',intensity=.5){stage.style.setProperty('--intensity',String(Math.max(0,Math.min(.65,Number(intensity)||0))));stage.dataset.emotion=e;stage.dataset.gesture=g}
function option(s,v,t){const o=el('option',t);o.value=v;s.append(o)}
const performanceController={epoch:0,frame:null,url:null,context:null,analyser:null,source:null,utterance:null,cancelWait:null,
 stop(){this.epoch++;if(this.cancelWait){this.cancelWait();this.cancelWait=null}cancelAnimationFrame(this.frame);this.frame=null;window.speechSynthesis?.cancel();const a=$('speechAudio');a.pause();a.removeAttribute('src');a.load();a.hidden=true;if(this.url)URL.revokeObjectURL(this.url);this.url=null;$('stage').style.setProperty('--mouth','0.04');setCue($('stage'));state('idle');},
 animate(epoch){let data=this.analyser?new Uint8Array(this.analyser.fftSize):null;const tick=t=>{if(epoch!==this.epoch)return;let value=.12+.6*Math.abs(Math.sin(t/110));if(this.analyser&&data&&settings.voice_engine==='macos'){this.analyser.getByteTimeDomainData(data);value=Math.min(1,Math.sqrt(data.reduce((s,v)=>s+(v-128)**2,0)/data.length)/20)}$('stage').style.setProperty('--mouth',String(Math.max(.04,value)));this.frame=requestAnimationFrame(tick)};this.frame=requestAnimationFrame(tick)},
 async segment(seg,epoch){const a=$('speechAudio');$('subtitle').textContent=seg.text;setCue($('stage'),seg.emotion,seg.gesture,seg.intensity);
  if(settings.voice_engine==='macos'){
   const r=await fetch('/api/speech',{method:'POST',headers:{'Content-Type':'application/json','X-Salesman-Local':'1'},body:JSON.stringify({text:seg.text,rate:current.rate})});if(!r.ok)throw Error('macOS 語音不可用，請在設定切換瀏覽器語音。');const b=await r.blob();if(epoch!==this.epoch)return;
   if(this.url)URL.revokeObjectURL(this.url);this.url=URL.createObjectURL(b);a.src=this.url;a.hidden=false;
   try{if(!this.context){this.context=new (window.AudioContext||window.webkitAudioContext)();this.source=this.context.createMediaElementSource(a);this.analyser=this.context.createAnalyser();this.analyser.fftSize=256;this.source.connect(this.analyser);this.analyser.connect(this.context.destination)}await this.context.resume()}catch{this.analyser=null}
   await new Promise((resolve,reject)=>{this.cancelWait=resolve;a.onended=()=>{cancelAnimationFrame(this.frame);$('stage').style.setProperty('--mouth','.04');state('idle');setCue($('stage'));resolve()};a.onerror=()=>reject(Error('音訊播放失敗。'));a.onplay=()=>{if(epoch!==this.epoch)return;setCue($('stage'),seg.emotion,seg.gesture,seg.intensity);state('speaking');this.animate(epoch)};a.onpause=()=>{cancelAnimationFrame(this.frame);$('stage').style.setProperty('--mouth','.04');state('idle')};a.play().catch(()=>{state('idle');notify('瀏覽器需要你點擊下方音訊播放器後，才會開始播放。')})});
  }else{
   if(!('speechSynthesis'in window))throw Error('瀏覽器不支援語音合成，請使用文字聊天。');
   await new Promise((resolve,reject)=>{const u=new SpeechSynthesisUtterance(seg.text);this.utterance=u;this.cancelWait=resolve;u.lang='zh-TW';u.rate=current.rate;u.voice=speechSynthesis.getVoices().find(v=>v.voiceURI===current.voice)||null;u.onstart=()=>{if(epoch!==this.epoch)return;state('speaking');this.animate(epoch)};u.onboundary=e=>{if(epoch===this.epoch)$('subtitle').textContent=seg.text.slice(e.charIndex)};u.onend=resolve;u.onerror=e=>e.error==='canceled'||e.error==='interrupted'?resolve():reject(Error('瀏覽器語音播放失敗：'+e.error));speechSynthesis.speak(u)});
  }
  this.cancelWait=null;cancelAnimationFrame(this.frame);$('stage').style.setProperty('--mouth','.04');setCue($('stage'));
 },
 async play(performance){this.stop();if(!settings.voice_enabled)return;const epoch=this.epoch;
  try{for(const seg of performance.segments){if(epoch!==this.epoch)break;await this.segment(seg,epoch)}if(epoch===this.epoch){state('idle');$('subtitle').textContent=performance.spoken_text}}
  catch(e){if(epoch===this.epoch){this.stop();state('error');notify(e.message)}}
 }
};
function showPersona(){current=personas.find(p=>p.id===$('customerPersona').value);if(!current)return;AvatarStudio.mount($('avatar'),current);$('stage').dataset.scene=current.scene;$('avatarName').textContent=current.name;$('avatarTitle').textContent=current.title;$('subtitle').textContent='你好，我是 '+current.name+'，你的 AI 業務顧問。';state('idle')}
function fillSelectors(){for(const [id,activeOnly]of [['customerPersona',true],['adminPersona',false]]){const s=$(id),prev=s.value;s.replaceChildren();personas.filter(p=>!activeOnly||p.active).forEach(p=>option(s,p.id,p.name+(p.active?'':'（已停用）')));if([...s.options].some(o=>o.value===prev))s.value=prev}showPersona()}
async function newConversation(){await stopAll();if(cid)await api('/api/conversations/'+cid,{method:'DELETE'});cid=null;$('messages').replaceChildren(el('p','新的對話已準備好。','empty'));$('sources').replaceChildren();showPersona()}
async function stopAll(){recognition?.abort();performanceController.stop();if(cid&&busy)try{await api('/api/chat/'+cid+'/stop',{method:'POST'})}catch(e){notify(e.message)}abort?.abort();busy=false;$('send').disabled=false;state('idle')}
function bubble(text,role){$('messages').querySelector('.empty')?.remove();let b=el('div',text,'bubble '+role);$('messages').append(b);$('messages').scrollTop=$('messages').scrollHeight;return b}
function extractSpoken(raw){const m=raw.match(/"spoken_text"\s*:\s*"((?:\\.|[^"\\])*)/s);if(!m)return '';try{return JSON.parse('"'+m[1].replace(/\\$/,'')+'"')}catch{return m[1].replace(/\\n/g,'\n').replace(/\\"/g,'"')}}
async function submitChat(event){event.preventDefault();if(busy||!current)return;const text=$('chatInput').value.trim();if(!text)return;performanceController.stop();recognition?.abort();bubble(text,'user');$('chatInput').value='';const answer=bubble('正在整理資料…','assistant');state('thinking');setCue($('stage'),'thinking','thinking');busy=true;$('send').disabled=true;rawStream='';abort=new AbortController();
 try{
  const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json','X-Salesman-Local':'1'},body:JSON.stringify({persona_id:current.id,conversation_id:cid,message:text}),signal:abort.signal});if(!r.ok){const e=await r.json();throw Error(e.detail||'無法開始對話')}
  const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='',doneResult=null,streamError=null;
  while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let i;
   while((i=buffer.indexOf('\n\n'))!==-1){let chunk=buffer.slice(0,i);buffer=buffer.slice(i+2);if(!chunk.startsWith('data: '))continue;let d=JSON.parse(chunk.slice(6));
    if(d.type==='conversation'){cid=d.id;$('sources').replaceChildren();if(d.sources.length){$('sources').append(el('span','本次檢索依據：'));d.sources.forEach(s=>{const b=el('button',s.filename+' · 段落 '+s.paragraph);b.type='button';b.onclick=()=>showDocument(s.filename,s.text);$('sources').append(b)})}}
    if(d.type==='delta'){rawStream+=d.delta;answer.textContent=extractSpoken(rawStream)||'正在整理回答…';$('messages').scrollTop=$('messages').scrollHeight}
    if(d.type==='done'){doneResult=d.performance;answer.textContent=d.performance.spoken_text}
    if(d.type==='error')streamError=d.message;
    if(d.type==='stopped'){answer.textContent=extractSpoken(rawStream)||'已停止生成。'}
   }
  }
  if(streamError)throw Error(streamError);
  if(doneResult){state('idle');setCue($('stage'));$('subtitle').textContent=doneResult.spoken_text;performanceController.play(doneResult)}else if(!answer.textContent)answer.textContent='已停止生成。';
 }catch(e){if(e.name==='AbortError'){answer.textContent=extractSpoken(rawStream)||'已停止生成。';state('idle')}else{answer.textContent=e.message;answer.classList.add('error');state('error');setCue($('stage'))}}
 finally{busy=false;$('send').disabled=false;abort=null}
}
function field(container,key,label,value,type='text',choices=null,wide=false,onChange=null){const wrap=el('div',undefined,'field'+(wide?' wide':'')),l=el('label',label),id='field-'+key;l.htmlFor=id;let input;
 if(choices){input=el('select');choices.forEach(c=>Array.isArray(c)?option(input,c[0],c[1]):option(input,c,c))}else input=el(type==='textarea'?'textarea':'input');input.id=id;if(type!=='textarea'&&!choices)input.type=type;if(type==='checkbox')input.checked=!!value;else input.value=value??'';if(type==='textarea'){input.rows=3;input.maxLength=12000}if(type==='number'){input.step='.05';input.min='.6';input.max='1.4'}input.addEventListener('input',()=>{const v=type==='checkbox'?input.checked:type==='number'?Number(input.value):input.value;if(onChange)onChange(v);else draft[key]=v;previewDraft()});wrap.append(l,input);container.append(wrap);return input}
function previewDraft(){if(!draft)return;document.querySelector('.preview-top a').href='/?persona='+draft.id;AvatarStudio.mount($('previewAvatar'),draft);$('previewStage').dataset.scene=draft.scene;$('previewName').textContent=draft.name}
function renderDraft(){$('identityFields').replaceChildren();$('salesBrainFields').replaceChildren();
 const labels={name:'姓名',title:'職稱',gender:'顯示性別',age:'約略年齡層',task:'角色任務',tone:'語氣',traits:'個性特質',product:'產品資訊',rules:'回覆原則',prohibitions:'禁止事項',cta:'行動呼籲'};
 for(const [k,l]of Object.entries(labels))field($('identityFields'),k,l,draft[k],['task','product','rules','prohibitions','cta'].includes(k)?'textarea':'text',null,['task','product','rules','prohibitions','cta'].includes(k));
 field($('identityFields'),'scene','預設場景',draft.scene,'text',scenes.map(s=>[s.id,s.name]));field($('identityFields'),'rate','語速',draft.rate,'number');
 const voices=window.speechSynthesis?.getVoices()||[];field($('identityFields'),'voice','瀏覽器聲音（macOS 模式使用系統預設）',draft.voice,'text',[['','系統預設'],...voices.map(v=>[v.voiceURI,v.name+' · '+v.lang])],true);field($('identityFields'),'active','啟用此角色',draft.active,'checkbox');
 const brain={persona_category:'人格類型',sales_philosophy:'銷售信念',sales_strategy:'銷售流程',decision_logic:'判斷邏輯',objection_strategy:'異議處理',catchphrases:'代表話術'};
 for(const[k,l]of Object.entries(brain))field($('salesBrainFields'),k,l,draft[k],'textarea',null,true);
 $('systemPrompt').value=draft.system_prompt;renderAvatarFields();previewDraft();
}
function loadDraft(){const p=personas.find(p=>p.id===$('adminPersona').value);if(!p)return;draft=structuredClone(p);renderDraft()}
function showPersonaPreset(p){const box=$('personaPresetPreview');box.replaceChildren();const copy=el('div');copy.append(el('span',p.category,'eyebrow'),el('h3',p.name+'｜'+p.tagline),el('p',p.flow,'preset-flow'),el('p',p.persona.sales_philosophy,'muted'));const apply=el('button','套用這套 Sales Brain','btn primary');apply.type='button';apply.onclick=()=>{const keep={id:draft.id,product:draft.product,image_id:draft.image_id,avatar:draft.avatar,active:draft.active};draft={...draft,...structuredClone(p.persona),...keep};renderDraft();notify('已套用「'+p.name+'」模板；確認內容後再儲存角色。')};box.append(copy,apply);box.hidden=false}
function renderPersonaPresets(){$('personaPresetGrid').replaceChildren();personaPresets.forEach(p=>{const b=el('button',undefined,'persona-preset');b.type='button';b.append(el('strong',p.name),el('span',p.category),el('small',p.flow));b.onclick=()=>showPersonaPreset(p);$('personaPresetGrid').append(b)})}
function renderAvatarFields(){$('avatarFields').replaceChildren();const choices={face:[['round','圓臉'],['oval','橢圓臉'],['square','方臉'],['long','長臉']],eyes:[['almond','杏眼'],['round','圓眼'],['narrow','細長']],brows:[['straight','平眉'],['arched','弧眉'],['soft','柔和']],nose:[['small','小巧'],['straight','直鼻'],['rounded','圓潤']],mouth:[['soft','自然'],['wide','較寬'],['small','較小']],hair:[['short','短髮'],['side','側分'],['bob','短鮑伯'],['long','長髮'],['wave','波浪'],['crop','俐落短髮'],['bun','髮髻'],['curtain','中分']],outfit:[['blazer','外套'],['shirt','襯衫'],['knit','針織']]};const labels={face:'臉型',width:'臉寬',chin:'下巴比例',eyes:'眼型',brows:'眉型',nose:'鼻型',mouth:'嘴型',hair:'髮型',skin:'膚色',hair_color:'髮色',glasses:'眼鏡',outfit:'服裝',color:'服裝配色'};
 for(const[k,l]of Object.entries(labels)){const type=k==='glasses'?'checkbox':['width','chin'].includes(k)?'number':['skin','hair_color','color'].includes(k)?'color':'text';let f=field($('avatarFields'),'avatar-'+k,l,draft.avatar[k],type,choices[k],false,v=>draft.avatar[k]=v);if(type==='number'){f.min='.85';f.max='1.15'}}
}
async function saveDraft(){draft.system_prompt=$('systemPrompt').value;const id=draft.id,body={...draft};delete body.id;const p=await api('/api/personas/'+id,{method:'PUT',body:JSON.stringify(body)});personas=personas.map(x=>x.id===id?p:x);fillSelectors();notify('角色已儲存在這部電腦。')}
function showDocument(name,text){$('docTitle').textContent=name;$('docContent').textContent=text;$('docDialog').showModal()}
async function documents(){const docs=await api('/api/knowledge');$('documentList').replaceChildren();$('knowledgeSummary').textContent=docs.length?`共 ${docs.length} 份文件已完成索引。`:'尚未加入知識文件；先上傳一份產品資料開始。';if(!docs.length)$('documentList').append(el('p','目前沒有文件。','muted'));for(const d of docs){const r=el('div',undefined,'doc-row');r.append(el('strong',d.name),el('small',`${(d.size/1024).toFixed(1)} KB · 已索引 ${d.chunks} 段 · ${new Date(d.updated).toLocaleString('zh-TW')}`));const view=el('button','查看','btn'),del=el('button','刪除','btn danger');view.onclick=guard(async()=>{const chunks=await api('/api/knowledge/'+d.id);showDocument(d.name,chunks.map(c=>'段落 '+c.n+'\n'+c.text).join('\n\n'))});del.onclick=guard(async()=>{await stopAll();await api('/api/knowledge/'+d.id,{method:'DELETE'});await documents();notify('文件與保留的對話脈絡已刪除。')});r.append(view,del);$('documentList').append(r)}}
function guard(fn){return async(...args)=>{try{await fn(...args)}catch(e){notify(e.message)}}}
async function checkAccount(){const b=$('recheck');b.disabled=true;$('accountStatus').textContent='正在透過官方 App Server 檢查…';try{const a=await api('/api/account/recheck',{method:'POST'});$('accountStatus').textContent=a.logged_in?'已透過 ChatGPT 登入'+(a.plan?' · '+a.plan:''):'未使用 ChatGPT 登入，請執行 codex login。';models=await api('/api/models');$('modelSelect').replaceChildren();option($('modelSelect'),'','使用官方預設模型');models.forEach(m=>option($('modelSelect'),m.model,m.displayName||m.model));$('modelSelect').value=settings.model;fillEfforts();if(a.logged_in){const limits=await api('/api/account/limits');$('limitStatus').replaceChildren(el('h3','訂閱額度'));for(const [bucket,windows]of Object.entries(limits)){for(const [name,w]of Object.entries(windows)){if(!w)continue;const row=el('div',undefined,'status-line');row.append(el('span',bucket+' · '+(w.windowDurationMins||name)+' 分鐘'),el('span',`已用 ${w.usedPercent??'未知'}% · ${w.resetsAt?new Date(w.resetsAt*1000).toLocaleString('zh-TW')+' 重置':'重置時間未提供'}`));$('limitStatus').append(row)}}}}catch(e){$('accountStatus').textContent=e.message}finally{b.disabled=false;await health()}}
function fillEfforts(){const m=models.find(m=>m.model===$('modelSelect').value)||models.find(m=>m.isDefault);$('effortSelect').replaceChildren();const list=m?.supportedReasoningEfforts||[{reasoningEffort:'low'}];list.forEach(e=>option($('effortSelect'),e.reasoningEffort,e.reasoningEffort));$('effortSelect').value=list.some(e=>e.reasoningEffort===settings.effort)?settings.effort:m?.defaultReasoningEffort||'low'}
async function health(){const h=await api('/api/health');$('healthStatus').replaceChildren();for(const[k,n]of [['web','本機網頁'],['sqlite','SQLite 資料庫'],['codex_cli','Codex CLI'],['app_server','App Server']]){const r=el('div',undefined,'status-line');r.append(el('span',n),el('span',h[k]?'可用':'尚未就緒'));$('healthStatus').append(r)}}
function refreshVoices(){const s=$('field-voice');if(!s||!draft)return;const v=draft.voice;s.replaceChildren();option(s,'','系統預設');(window.speechSynthesis?.getVoices()||[]).forEach(x=>option(s,x.voiceURI,x.name+' · '+x.lang));if([...s.options].some(o=>o.value===v))s.value=v}
function setupSpeech(){if(window.speechSynthesis){speechSynthesis.addEventListener('voiceschanged',refreshVoices);refreshVoices()}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;$('mic').disabled=!SR;$('speechSupport').textContent=(SR?'語音輸入可用；點擊後才要求麥克風。':'此瀏覽器不支援語音辨識，可繼續文字聊天。')+('speechSynthesis'in window?' 瀏覽器語音合成可用。':' 瀏覽器語音合成不支援。');
 if(SR){recognition=new SR();recognition.lang='zh-TW';recognition.interimResults=true;recognition.onstart=()=>{state('listening');setCue($('stage'),'attentive','still')};recognition.onresult=e=>{$('chatInput').value=Array.from(e.results).map(r=>r[0].transcript).join('')};recognition.onend=()=>{if(!busy)state('idle')};recognition.onerror=e=>{notify('語音輸入失敗：'+e.error+'。你仍可輸入文字。');state('error')};$('mic').onclick=guard(async()=>{await stopAll();recognition.start()})}}
function updateEmbedCode(){const src=location.origin+'/embed';$('embedCode').value=`<iframe src="${src}" title="AI 業務顧問" width="100%" height="760" style="border:0;border-radius:16px" allow="microphone"></iframe>`;$('previewEmbed').classList.toggle('disabled',!$('embedEnabled').checked);$('previewEmbed').setAttribute('aria-disabled',String(!$('embedEnabled').checked))}
function embedOrigins(){return $('embedOrigins').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
async function init(){const route=location.pathname,isChat=route==='/'||route==='/embed';document.body.classList.toggle('embed-mode',route==='/embed');document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===route));$('customer').hidden=!isChat;$('admin').hidden=route!=='/admin';$('knowledgePage').hidden=route!=='/knowledge';$('setup').hidden=route!=='/setup';const titles={'/admin':['現在就打造你的 AI 業務團隊。','幾分鐘設定角色、產品與話術，立即看見可用的 AI 業務。','打造 AI 業務'],'/knowledge':['讓每位 AI 業務，都說出正確的產品答案。','集中管理產品文件；更新一次，所有角色都能在對話中檢索。','產品知識庫'],'/setup':['只要有 GPT 訂閱，立即讓你的 AI 銷售人員動起來。','登入一次、不用 API key，就能開始使用你的本機 AI 業務工作室。','啟動 AI 業務']};if(titles[route]){const[t,s,b]=titles[route];$('pageTitle').textContent=t;$('pageSubtitle').textContent=s;$('breadcrumb').textContent=b}
 [personas,presets,personaPresets,scenes,settings]=await Promise.all(['/api/personas','/api/avatar/presets','/api/persona-presets','/api/scenes','/api/settings'].map(p=>api(p)));fillSelectors();const requested=new URLSearchParams(location.search).get('persona');if(personas.some(p=>p.id===requested&&p.active)){$('customerPersona').value=requested;showPersona()}loadDraft();renderPersonaPresets();setupSpeech();const template=await api('/api/persona-template');$('safetyPreview').textContent='共用銷售原則（始終生效）：\n'+template.sales_base+'\n\n固定安全規範（始終生效）：\n'+template.safety;$('restorePrompt').onclick=()=>{$('systemPrompt').value=template.system_prompt;draft.system_prompt=template.system_prompt;notify('已恢復預設，請儲存角色。')};
 presets.forEach(p=>{const b=el('button',undefined,'preset');b.title=p.name;b.append(AvatarStudio.render(p.avatar),el('span',p.name));b.onclick=()=>{draft.avatar=structuredClone(p.avatar);draft.image_id=null;renderAvatarFields();previewDraft()};$('presetGrid').append(b)});
 const tests=[['眨眼','neutral','still'],['微笑','smile','still'],['思考','thinking','thinking'],['關心','empathetic','small_nod'],['興奮','excited','open_hand'],['點頭','smile','nod'],['搖頭','neutral','shake'],['聆聽','attentive','still'],['介紹產品','confident','present_product'],['結束','smile','closing']];
 tests.forEach(([n,e,g])=>{const b=el('button',n,'btn');b.onclick=()=>{clearTimeout(previewTimer);$('previewStage').getAnimations({subtree:true}).filter(a=>a.animationName!=='breathe').forEach(a=>a.cancel());setCue($('previewStage'),e,g);if(n==='眨眼')$('previewAvatar').querySelector('.eye-layer')?.animate([{transform:'scaleY(1)'},{transform:'scaleY(.02)'},{transform:'scaleY(1)'}],{duration:350});previewTimer=setTimeout(()=>setCue($('previewStage')),2200)};$('motionTests').append(b)});
 $('stopPreview').onclick=()=>{clearTimeout(previewTimer);$('previewStage').getAnimations({subtree:true}).forEach(a=>a.cancel());setCue($('previewStage'))};
 $('chatForm').onsubmit=submitChat;$('stop').onclick=guard(stopAll);$('clearChat').onclick=guard(newConversation);$('customerPersona').onchange=guard(newConversation);$('adminPersona').onchange=()=>{clearTimeout(previewTimer);setCue($('previewStage'));loadDraft()};$('savePersona').onclick=guard(saveDraft);
 $('newPersona').onclick=guard(async()=>{const p=await api('/api/personas',{method:'POST',body:JSON.stringify({name:'新業務顧問'})});personas.push(p);fillSelectors();$('adminPersona').value=p.id;loadDraft()});$('duplicatePersona').onclick=guard(async()=>{const body={...draft,name:draft.name+' 副本'};delete body.id;const p=await api('/api/personas',{method:'POST',body:JSON.stringify(body)});personas.push(p);fillSelectors();$('adminPersona').value=p.id;loadDraft();notify('已複製角色。')});$('disablePersona').onclick=guard(async()=>{await api('/api/personas/'+draft.id,{method:'DELETE'});personas=await api('/api/personas');fillSelectors();loadDraft();notify('角色已停用。')});
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>{x.classList.toggle('active',x===b);$(x.dataset.tab).hidden=x!==b})});
 $('imageUpload').onchange=guard(async()=>{const f=$('imageUpload').files[0];if(!f)return;const form=new FormData();form.append('file',f);const r=await api('/api/avatar/upload',{method:'POST',body:form});draft.image_id=r.image_id;previewDraft();notify('已上傳靜態圖片，請儲存角色。')});$('removeImage').onclick=()=>{draft.image_id=null;previewDraft()};
 $('knowledgeUpload').onchange=guard(async()=>{const input=$('knowledgeUpload'),f=input.files[0];if(!f)return;if(f.size>20*1024*1024)throw Error('檔案超過 20 MB。');input.disabled=true;try{const form=new FormData();const ext=f.name.split('.').pop().toLowerCase(),types={txt:'text/plain',md:'text/markdown',pdf:'application/pdf',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'};form.append('file',new Blob([f],{type:f.type||types[ext]}),f.name);const r=await api('/api/knowledge/upload',{method:'POST',body:form});await documents();notify(r.unchanged?'內容相同，保留既有索引。':'知識文件已完成索引。')}finally{input.disabled=false;input.value=''}});
 $('closeDoc').onclick=()=>$('docDialog').close();$('recheck').onclick=checkAccount;$('modelSelect').onchange=fillEfforts;
 if(settings.model){option($('modelSelect'),settings.model,settings.model+'（已儲存，重新檢查可用性）');$('modelSelect').value=settings.model}if(settings.effort!=='low'){option($('effortSelect'),settings.effort,settings.effort);$('effortSelect').value=settings.effort}$('responseLength').value=settings.response_length;$('historyTurns').value=settings.history_turns;$('ragTopK').value=settings.rag_top_k;$('voiceEngine').value=settings.voice_engine;$('voiceEnabled').checked=settings.voice_enabled;$('embedEnabled').checked=settings.embed_enabled;$('embedOrigins').value=settings.embed_origins.join('\n');updateEmbedCode();$('embedEnabled').onchange=updateEmbedCode;
 $('settingsForm').onsubmit=guard(async e=>{e.preventDefault();const s={...settings,model:$('modelSelect').value,effort:$('effortSelect').value,response_length:$('responseLength').value,history_turns:Number($('historyTurns').value),rag_top_k:Number($('ragTopK').value),voice_engine:$('voiceEngine').value,voice_enabled:$('voiceEnabled').checked};settings=await api('/api/settings',{method:'PUT',body:JSON.stringify(s)});notify('對話與語音設定已儲存。')});
 $('saveEmbed').onclick=guard(async()=>{settings=await api('/api/settings',{method:'PUT',body:JSON.stringify({...settings,embed_enabled:$('embedEnabled').checked,embed_origins:embedOrigins()})});$('embedOrigins').value=settings.embed_origins.join('\n');updateEmbedCode();notify('嵌入設定已儲存。')});$('copyEmbed').onclick=guard(async()=>{await navigator.clipboard.writeText($('embedCode').value);notify('iframe 程式碼已複製。')});
 if(route==='/knowledge')await documents();if(route==='/setup')await health();
}
function renderMarketingHero(){
 if(location.pathname!=='/'||document.querySelector('.marketing-hero'))return;
 $('pageTitle').textContent='把每一次詢問，變成一次成交機會。';
 $('pageSubtitle').textContent='不用招募、不用排班，今天就讓你的 AI 業務開始工作。';
 $('breadcrumb').textContent='立即試用';
 const topAction=document.querySelector('.topbar .btn');
 if(topAction){topAction.href='/admin';topAction.textContent='立即打造 AI 業務 ↗'}
 const hero=el('section',undefined,'marketing-hero');
 const copy=el('div',undefined,'marketing-copy');
 copy.append(el('span','你的下一位業務，現在就能上線。','eyebrow'),el('h2','把每一次詢問，變成一次成交機會。'),el('p','把產品知識、銷售話術與品牌語氣交給 AI，立即開始一段可用的業務對話。','marketing-description'));
 const actions=el('div',undefined,'marketing-actions');
 const start=document.createElement('a');start.href='/admin';start.className='btn primary';start.textContent='立即打造我的 AI 業務 ↗';
 const chat=document.createElement('a');chat.href='#customer';chat.className='btn';chat.textContent='先試一輪對話';
 actions.append(start,chat);
 const points=el('div',undefined,'marketing-points');
 ['快速建立角色','產品資料可控','立即測試對話'].forEach(t=>points.append(el('span',t)));
 copy.append(actions,points,el('small','本機體驗版｜設定完成後即可在下方測試。','marketing-note'));
 const figure=el('figure',undefined,'marketing-visual');
 const img=document.createElement('img');img.src='/assets/product-preview.png';img.alt='AI Salesman 角色工作室畫面，展示角色設定與即時人物預覽';img.loading='lazy';
 figure.append(img,el('figcaption','從角色設定到即時預覽，一個畫面完成。'));
 hero.append(copy,figure);$('customer').before(hero);
}
window.addEventListener('pagehide',()=>{performanceController.stop();recognition?.abort();abort?.abort()});renderMarketingHero();init().catch(e=>notify(e.message));
