

'use strict';
/* Image presets: embedded assets, no network needed. Stock portraits represent fictional employees. */
const IMAGE_ASSETS={"strategist":"/assets/legacy-1.jpg","advisor":"/assets/legacy-2.jpg","energetic":"/assets/legacy-3.jpg","alex":"/assets/legacy-4.jpg","expert":"/assets/legacy-5.jpg","female":"/assets/legacy-6.jpg","luxury":"/assets/legacy-7.jpg"};
const personaImageMap={wolf:{male:'alex',female:'luxury'},advisor:{male:'expert',female:'advisor'},strategist:{male:'strategist',female:'luxury'},luxury:{male:'alex',female:'luxury'},energetic:{male:'energetic',female:'female'},expert:{male:'expert',female:'advisor'}};
/* Utilities */
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s)),clone=x=>JSON.parse(JSON.stringify(x));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=x=>LABELS[x]||String(x).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const icon=x=>`<svg class="icon" aria-hidden="true"><use href="#i-${x}"/></svg>`;
const pathGet=(obj,path)=>path.split('.').reduce((o,k)=>o?.[k],obj);
function pathSet(obj,path,value){const keys=path.split('.');let dest=obj;for(const key of keys.slice(0,-1))dest=dest[key];dest[keys.at(-1)]=value;}
let toastTimer,saveTimer,chatTimer,voiceTimer,generationBusy=false,chatEpoch=0,recognition=null;
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4200);}
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function info(heading,content){$('#info-title').textContent=heading;$('#info-content').innerHTML=content;$('#info-dialog').showModal();}
const money=n=>'$'+Math.round(n).toLocaleString('en-US');
function numberPrice(){const raw=salesman.product.price.replaceAll(',','');const match=raw.match(/\d+(?:\.\d+)?/);return match?Number(match[0]):null;}
/* Persona presets */
const TRAIT_KEYS=['confidence','aggressiveness','empathy','directness','energy','urgency','patience','humor'];
const METHODS={"consultative":"顧問式銷售","spin":"SPIN 提問法","challenger":"挑戰式銷售","solution":"解決方案銷售","aida":"AIDA 注意力引導","pas":"PAS 痛點說服","straight_line":"直線式銷售","high_energy_closing":"高能量成交","data_driven":"數據驅動銷售","custom":"自訂"};
const RULES={"questions":"先問問題，再介紹產品","pain":"先理解客戶痛點","quantify":"量化問題的影響","roi":"計算投資報酬 ROI","compare":"比較替代方案","objections":"主動處理異議","urgency":"協助建立合理的行動時機","next":"清楚邀請客戶走向下一步","no_discount":"不要立刻提供折扣","no_scarcity":"不可虛構稀缺性","honesty":"不可歪曲或虛構資訊","disclose":"始終表明這是一位 AI 業務"};
const GOALS={"purchase":"直接購買","book_demo":"預約 Demo","leave_contact":"留下聯絡資料","request_quote":"索取報價","free_trial":"開始免費試用","whatsapp":"WhatsApp","call_sales":"聯絡業務","human":"轉真人"};
const PRESETS={
 wolf:{label:'Wolf of Wall Street',subtitle:'High-Energy Closer',zh:'激情成交型',emoji:'🔥',name:'Alex Carter',gender:'male',age:38,style:'wall_street',outfit:'white_shirt',environment:'luxury_office',energy:'intense',traits:['Confident','Direct','High-energy'],values:[98,88,48,95,100,88,35,45],extras:{charisma:100,persuasiveness:98},voice:['Marcus','fast','persuasive','short_direct'],methods:['consultative','high_energy_closing'],summary:'A high-energy closer who identifies customer pain, quantifies the business impact, and confidently moves qualified buyers toward action.',short:'Turns real business pain into forward momentum.',opening:'Let me ask you something. How much is your current customer service operation costing you every month? Before I show you a single feature, I want to know whether there’s actually a business case here.',discovery:'Find pain, money, time, urgency, and who makes the decision.',pitch:'Connect pain to value and business impact before introducing the product.',closing:'Let’s take the next logical step and validate the business case together.',image_description:'Original fictional charismatic Wall Street sales closer, male around 38, dark slicked-back hair, crisp white dress shirt, open collar, luxury watch, leaning forward with a pen and a persuasive open-hand gesture. Warm cinematic Manhattan executive office. Inspired by the high-energy sales atmosphere of The Wolf of Wall Street; not resembling a specific actor.'},
 advisor:{label:'Trusted Advisor',subtitle:'Warm Consultative Seller',zh:'溫暖顧問型',emoji:'🤝',name:'Sophia Bennett',gender:'female',age:39,style:'executive',outfit:'navy_suit',environment:'bright_office',energy:'calm',traits:['Empathetic','Patient','Warm'],values:[82,20,98,55,58,22,98,55],extras:{charisma:75,persuasiveness:70},voice:['Sophia','normal','calm','balanced'],methods:['consultative','solution'],summary:'A thoughtful consultant who prioritizes understanding the customer before recommending a solution. If it is not a fit, she will tell you.',short:'Earns trust by listening before recommending.',opening:'Before I recommend anything, I’d love to understand how your team handles customer service today.',discovery:'Listen to the customer’s workflow and the outcome they hope for.',pitch:'Offer a recommendation only after confirming a real fit.',closing:'The next step I’d suggest is a short demo tailored to your workflow.',image_description:'Original fictional warm female consultant around 39, navy blazer, light shirt, relaxed smile and open hands, bright modern office with natural daylight.'},
 strategist:{label:'The Strategist',subtitle:'Analytical Sales Expert',zh:'冷靜分析型',emoji:'📊',name:'Daniel Brooks',gender:'male',age:36,style:'modern_saas',outfit:'navy_suit',environment:'modern_office',energy:'calm',traits:['Analytical','Precise','Logical'],values:[90,32,55,80,48,30,82,20],extras:{analytical:100},voice:['James','normal','professional','detailed'],methods:['data_driven','consultative'],summary:'A structured advisor who uses facts, comparisons, and ROI to help customers make confident decisions.',short:'Builds a business case, one clear insight at a time.',opening:'Let’s start with the numbers. How many support requests does your team handle every month?',discovery:'Establish the baseline, compare options, and identify risks.',pitch:'Use transparent assumptions to show measurable business value.',closing:'Let’s use a demo to validate the assumptions and implementation fit.',image_description:'Original fictional analytical SaaS executive around 36, navy suit, modern glass office, precise calm expression, premium natural photography.'},
 luxury:{label:'Luxury Consultant',subtitle:'Premium Relationship Seller',zh:'高端精品型',emoji:'💎',name:'Olivia Hayes',gender:'female',age:41,style:'luxury',outfit:'dark_suit',environment:'luxury_showroom',energy:'balanced',traits:['Elegant','Attentive','Refined'],values:[95,28,82,58,42,20,92,30],extras:{sophistication:100},voice:['Olivia','slow','elegant','short_direct'],methods:['consultative','solution'],summary:'A polished relationship builder with a discerning eye for detail, creating thoughtful recommendations and a personal buying experience.',short:'Makes every recommendation feel considered.',opening:'Tell me what an exceptional experience would look like for you. I’ll help you find the right fit.',discovery:'Understand individual preferences and the desired experience.',pitch:'Present a considered selection that matches the customer’s priorities.',closing:'Would you like me to arrange a private consultation?',image_description:'Original fictional elegant female luxury consultant around 41, dark tailored suit, warm marble and dark wood showroom, composed and polished.'},
 energetic:{label:'Energetic Seller',subtitle:'Friendly High-Energy Seller',zh:'陽光激情型',emoji:'⚡',name:'Ethan Cole',gender:'male',age:29,style:'modern_saas',outfit:'business_casual',environment:'bright_office',energy:'energetic',traits:['Upbeat','Friendly','Enthusiastic'],values:[88,48,75,72,100,62,70,72],extras:{},voice:['Ethan','fast','energetic','balanced'],methods:['aida','solution'],summary:'An upbeat, approachable salesperson who makes product discovery feel easy and gets customers excited about what is possible.',short:'Brings positive energy to every conversation.',opening:'Hey! What’s the one thing you’d love to make easier for your team? Let’s see what’s possible.',discovery:'Explore the customer’s priorities in a friendly conversation.',pitch:'Show a relevant use case and make the benefit tangible.',closing:'Want to see it in action? Let’s find a next step that works for you.',image_description:'Original fictional friendly male SaaS salesperson around 29, business casual, bright office, warm smile, enthusiastic approachable expression.'},
 expert:{label:'Calm Expert',subtitle:'Professional Subject-Matter Expert',zh:'沉穩專家型',emoji:'🎓',name:'James Parker',gender:'male',age:48,style:'professional_expert',outfit:'dark_suit',environment:'dark_executive_office',energy:'calm',traits:['Experienced','Calm','Credible'],values:[95,18,68,75,32,15,95,18],extras:{authority:100},voice:['James','slow','professional','detailed'],methods:['solution','consultative'],summary:'An experienced subject-matter expert who explains complex products clearly, acknowledges trade-offs, and gives buyers room to decide.',short:'Turns complex decisions into clear next steps.',opening:'There are two things I’d look at before making that decision: your current setup, and whether it will scale. Where would you like to start?',discovery:'Understand the current architecture, constraints, and growth plans.',pitch:'Explain the trade-offs with clarity and grounded expertise.',closing:'A focused technical demo would help validate whether this is the right fit.',image_description:'Original fictional mature male industry expert around 48, executive dark suit, calm authoritative expression, refined dark executive office.'}
};
const EXAMPLES={wolf:'我要一個像華爾街之狼那種非常有激情的業務。\n男性，約 35～40 歲，白襯衫，高階華爾街 Sales 的形象。\n他非常有自信，說話快速、有感染力，擅長主導談話。\n遇到價格問題時不要立即降價，先算 ROI。\n遇到「我想再考慮」時，要找出真正沒有解決的 objection。\n對符合條件的客戶，要積極要求進入下一步。',analytical:'I want a calm, analytical and professional salesperson who explains ROI clearly and never pressures the customer.',warm:'I want a warm, empathetic female salesperson who listens carefully, is patient, and helps customers book a demo without pressure.'};
/* V2 localized presentation and swappable media presets. */
const LABELS={male:'男性',female:'女性',wall_street:'華爾街金融',executive:'企業主管',modern_saas:'現代 SaaS',luxury:'高端精品',casual:'休閒商務',tech_founder:'科技創辦人',professional_expert:'專業顧問',white_shirt:'白襯衫',dark_suit:'深色西裝',navy_suit:'海軍藍西裝',business_casual:'商務休閒',turtleneck:'高領上衣',luxury_office:'豪華辦公室',modern_office:'現代辦公室',bright_office:'明亮辦公室',dark_executive_office:'深色主管辦公室',studio:'攝影棚',luxury_showroom:'精品展示間',calm:'沉穩',balanced:'平衡',energetic:'有活力',intense:'高能量',slow:'慢速',normal:'一般',fast:'快速',professional:'專業',persuasive:'有說服力',elegant:'優雅',short_direct:'簡短直接',detailed:'詳細說明',confidence:'自信',aggressiveness:'成交積極度',empathy:'同理心',directness:'直接程度',energy:'能量',urgency:'推進節奏',patience:'耐心',humor:'幽默',charisma:'個人魅力',persuasiveness:'說服力',analytical:'分析能力',sophistication:'品味',authority:'專業權威',features:'功能',competitors:'競品',promotions:'優惠',restrictions:'限制'};
const ZH_PRESETS={
 wolf:{zh:'華爾街之狼式激情成交型',role:'高能量成交專家',traits:['自信','直接','高能量'],summary:'主動找到真正的痛點，用數字建立價值，再帶領合適的客戶走向下一步。積極成交，但始終尊重客戶的決定。',short:'先找痛點，再算價值，最後推進成交。',opening:'先不要急著看產品。我先問你一個問題。你現在這個問題，每個月到底正在花你多少錢？',discovery:'找到痛點、成本、時機與決策者。',pitch:'先談痛點與價值，再介紹產品。',closing:'下一步很簡單。我們用 20 分鐘，驗證這筆投資到底值不值得。',image_description:'原創虛構男性業務，約 38 歲，深色往後梳頭髮，白襯衫、開領、無領帶、高級腕錶。上半身前傾，直視鏡頭，手拿筆，另一手正在說服客戶。豪華曼哈頓金融辦公室，暖色電影光線，充滿自信與成交能量。不模仿特定演員或真實人物。'},
 advisor:{zh:'溫暖顧問型',role:'信任關係顧問',traits:['同理','耐心','溫暖'],summary:'先理解客戶，再提出建議。用耐心與真誠建立信任；不適合的方案，也會直接告訴客戶。',short:'認真傾聽，讓每個建議都貼近需求。',opening:'在我提出建議前，想先了解你的團隊目前怎麼工作。你最希望改善的是哪一件事？',discovery:'理解現有流程與期待的結果。',pitch:'確認適合，再提出具體建議。',closing:'如果你願意，我們可以安排一場依照你們流程設計的簡短 Demo。',image_description:'原創虛構女性顧問，約 39 歲，海軍藍外套、淺色襯衫，自然微笑、雙手開放姿態。明亮辦公室，自然光，溫暖可信任，上半身與雙手入鏡。'},
 strategist:{zh:'冷靜分析型',role:'數據型銷售專家',traits:['分析','精準','理性'],summary:'用透明的假設、數據比較與 ROI，協助客戶評估價值、風險及導入條件。',short:'把複雜問題，整理成可驗證的決策。',opening:'我們先從數字開始。你的團隊每個月處理多少客服需求？目前最想改善哪個指標？',discovery:'建立基準、比較選項與辨識風險。',pitch:'用可驗證的假設呈現商業價值。',closing:'建議下一步用 Demo 驗證兩件事：自動化比例，以及導入是否符合你們的流程。',image_description:'原創虛構男性 SaaS 主管，約 36 歲，海軍藍西裝，冷靜、精準、具分析力。現代玻璃辦公室，簡潔環境，上半身與雙手入鏡，正面看鏡頭。'},
 luxury:{zh:'高端精品顧問型',role:'高端體驗顧問',traits:['優雅','細膩','品味'],summary:'重視偏好、體驗與細節。以精準推薦與從容的節奏，為客戶找到真正符合標準的選擇。',short:'從容了解偏好，精準呈現合適選擇。',opening:'你心目中理想的體驗是什麼樣子？先讓我了解你的標準，再一起挑選合適的方案。',discovery:'理解偏好、標準與期待體驗。',pitch:'提供精準、周到的個人化推薦。',closing:'這個方向符合你的期待的話，我可以為你安排一次專屬諮詢。',image_description:'原創虛構女性精品顧問，約 41 歲，剪裁俐落的深色西裝，舉止優雅，正面看鏡頭。大理石與深色木質展示間，暖光，上半身及雙手入鏡。'},
 energetic:{zh:'陽光激情型',role:'活力型銷售夥伴',traits:['友善','正向','熱情'],summary:'以明亮、親切的節奏探索需求，把產品好處變成容易理解、讓人期待的使用情境。',short:'讓產品探索變得輕鬆，而且充滿期待。',opening:'太好了！如果能讓團隊的一件事變得更輕鬆，你最想先改變什麼？我們一起看看！',discovery:'用輕鬆對話找到最有感的需求。',pitch:'用貼近生活的情境呈現好處。',closing:'要不要直接看一次實際情境？一起找個適合你的下一步！',image_description:'原創虛構男性 SaaS 業務，約 29 歲，商務休閒，明亮辦公室，親切笑容與活潑手勢。上半身與雙手入鏡，正面看鏡頭，陽光有活力。'},
 expert:{zh:'沉穩專家型',role:'資深產業顧問',traits:['成熟','穩定','專業'],summary:'以清楚的分析解釋複雜產品，誠實討論取捨與限制，讓客戶有足夠資訊做決定。',short:'解釋取捨，穩健地走向下一個決策。',opening:'做決定之前，我會先看兩件事：現在的做法，以及未來能不能擴充。你想先從哪裡開始？',discovery:'理解架構、限制與成長規劃。',pitch:'說清楚效益、風險與必要條件。',closing:'我們可以安排一場聚焦實際需求的技術 Demo，再決定是否值得往下走。',image_description:'原創虛構成熟男性專家，約 48 歲，深色西裝，沉穩、權威但親切。精緻主管辦公室，上半身與雙手入鏡，正面看鏡頭。'}
};
Object.entries(ZH_PRESETS).forEach(([key,localized])=>Object.assign(PRESETS[key],localized));
EXAMPLES.analytical='我要一位冷靜、擅長數據分析且專業的業務員，能清楚解釋 ROI，絕不對客戶施壓。';
EXAMPLES.warm='我要一位溫暖、有同理心的女性業務。她會耐心傾聽、理解需求，再邀請適合的客戶預約 Demo。';
const DEFAULT_PRODUCT_ZH={name:'Customer Service AI',description:'協助企業自動處理重複客服問題的 AI 客服平台，讓團隊把時間留給真正需要人的工作。',price:'US$499／月',targetCustomer:'50～500 人規模的企業',benefits:['全天候客服','降低客服成本','加快回覆速度','CRM 整合'],features:['自動回答問題','產品知識庫','CRM 整合'],competitors:[],promotions:[],restrictions:['不保證節省金額；所有估算都必須以客戶實際資料驗證。']};
const DEFAULT_OBJECTIONS_ZH=[{objection:'太貴了',strategy:'先計算 ROI，再討論價格。',never:'立刻提供折扣。',response_style:'直接但尊重。'},{objection:'我再考慮',strategy:'找出還沒有被解決的具體疑慮。',never:'施壓或忽視客戶的顧慮。',response_style:'好奇、耐心、尊重。'},{objection:'我們已經有其他方案',strategy:'先詢問現有方案的優點與不足，再比較真正重要的差異。',never:'虛構競品缺點。',response_style:'客觀、以需求為主。'}];
const VARIANT_META={wolf:[{gender:'male',age:38,style:'wall_street',outfit:'white_shirt',environment:'luxury_office',energy:'intense',label:'男性 · 白襯衫 · 華爾街'},{gender:'female',age:38,style:'wall_street',outfit:'white_shirt',environment:'dark_executive_office',energy:'intense',label:'女性 · 白襯衫 · 金融主管'}],advisor:[{gender:'female',age:39,style:'executive',outfit:'navy_suit',environment:'bright_office',energy:'calm',label:'女性 · 海軍藍 · 自然光'},{gender:'male',age:45,style:'executive',outfit:'business_casual',environment:'modern_office',energy:'balanced',label:'男性 · 休閒外套 · 顧問'}],strategist:[{gender:'male',age:36,style:'modern_saas',outfit:'navy_suit',environment:'modern_office',energy:'calm',label:'男性 · 海軍藍 · 玻璃辦公室'},{gender:'female',age:42,style:'modern_saas',outfit:'dark_suit',environment:'modern_office',energy:'calm',label:'女性 · 灰西裝 · 分析型'}],luxury:[{gender:'female',age:41,style:'luxury',outfit:'dark_suit',environment:'luxury_showroom',energy:'balanced',label:'女性 · 深色西裝 · 精品'},{gender:'male',age:48,style:'luxury',outfit:'dark_suit',environment:'luxury_office',energy:'calm',label:'男性 · 訂製西裝 · 貴賓室'}],energetic:[{gender:'male',age:29,style:'modern_saas',outfit:'business_casual',environment:'bright_office',energy:'energetic',label:'男性 · 商務休閒 · 明亮'},{gender:'female',age:28,style:'casual',outfit:'business_casual',environment:'studio',energy:'energetic',label:'女性 · 活力休閒 · 工作室'}],expert:[{gender:'male',age:48,style:'professional_expert',outfit:'dark_suit',environment:'dark_executive_office',energy:'calm',label:'男性 · 資深主管 · 深色'},{gender:'female',age:50,style:'professional_expert',outfit:'navy_suit',environment:'modern_office',energy:'calm',label:'女性 · 專業顧問 · 藏書辦公室'}]};
const PORTRAIT_SHEETS={"wolf":"/assets/legacy-8.png","advisor":"/assets/legacy-9.png","strategist":"/assets/legacy-10.png","luxury":"/assets/legacy-11.png","energetic":"/assets/legacy-12.png","expert":"/assets/legacy-13.png"};
const UI_STATE={websiteOpen:false,websiteWidgetOpen:false,websiteEntry:'avatar',fallbackOpen:false};
const runtime={recognition:null,recognitionReject:null,responseEpoch:0,revealEpoch:0,voiceEpoch:0,activeCall:false,generating:false,voicePreviewTimer:null};

/* Centralized state */
function defaultStateV1(){const p=PRESETS.wolf;return {version:1,preset:'wolf',description:EXAMPLES.wolf,identity:{name:p.name,archetype:p.label,title:p.subtitle},appearance:{gender:p.gender,age:p.age,style:p.style,outfit:p.outfit,environment:p.environment,energy:p.energy,image_description:p.image_description,image_variant:0,image_override:''},personality:Object.assign(Object.fromEntries(TRAIT_KEYS.map((k,i)=>[k,p.values[i]])),p.extras),voice:{name:p.voice[0],speed:p.voice[1],tone:p.voice[2],conversationStyle:p.voice[3]},product:{name:'Customer Service AI',description:'AI customer service platform that helps companies automate repetitive support questions.',price:'$499/month',targetCustomer:'Companies with 50–500 employees',benefits:['24/7 Support','Reduce Support Cost','Faster Response','CRM Integration'],features:['Automated answers','Knowledge base','CRM integration'],competitors:[],promotions:[],restrictions:['No guaranteed savings; validate estimates with customer data.']},sales:{methods:clone(p.methods),rules:Object.keys(RULES),goal:'book_demo',cta:'Book a Demo',custom:''},objections:[{objection:"It's too expensive.",strategy:'Calculate ROI before discussing discount.',never:'Immediately offer a discount.',response_style:'Direct but respectful.'},{objection:'I need to think about it.',strategy:'Identify the specific unresolved concern.',never:'Pressure the customer or dismiss their concern.',response_style:'Curious and respectful.'},{objection:'We already use another solution.',strategy:'Ask what they like and dislike about their current solution, then compare relevant differences.',never:'Invent competitor weaknesses.',response_style:'Objective and consultative.'}],knowledge:{url:'',imported:false,files:[]},meta:{generated:false,device:'desktop'},chat:{open:false,plan:'Pro',messages:[],quick:[],stage:'discovery',team:32,busy:false}};}
const STORAGE_KEY='ai-salesman-studio-v1';let storageAvailable=true;
function mergeKnown(base,input){for(const k of Object.keys(base)){if(!(k in input))continue;if(Array.isArray(base[k])){if(Array.isArray(input[k]))base[k]=input[k];}else if(base[k]&&typeof base[k]==='object'){if(input[k]&&typeof input[k]==='object'&&!Array.isArray(input[k]))mergeKnown(base[k],input[k]);}else if(typeof input[k]===typeof base[k])base[k]=input[k];}return base;}
function loadStateV1(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const data=JSON.parse(raw);if(data.version!==1||!PRESETS[data.preset])return defaultState();const state=mergeKnown(defaultState(),data);for(const k of TRAIT_KEYS)state.personality[k]=Math.max(0,Math.min(100,Number(state.personality[k])||0));if(!GOALS[state.sales.goal])state.sales.goal='book_demo';state.chat.busy=false;state.chat.open=false;state.chat.messages=state.chat.messages.filter(m=>m&&typeof m.text==='string'&&['user','assistant','roi'].includes(m.role));state.objections=state.objections.filter(o=>o&&typeof o.objection==='string');return state;}}catch(e){storageAvailable=false;}return defaultState();}
let salesman=loadState();
/* Local storage */
/* Render functions */
function selectField(label,path,options){const val=pathGet(salesman,path);return `<div class="field"><label for="${path}">${label}</label><select id="${path}" data-bind="${path}">${options.map(x=>{const [v,t]=Array.isArray(x)?x:[x,title(x)];return `<option value="${esc(v)}" ${val===v?'selected':''}>${esc(t)}</option>`;}).join('')}</select></div>`;}
function textField(label,path,multi=false){const val=pathGet(salesman,path);const text=Array.isArray(val)?val.join('\n'):val;return `<div class="field"><label for="${path}">${label}</label>${multi?`<textarea id="${path}" data-bind="${path}" ${Array.isArray(val)?'data-array="true"':''}>${esc(text)}</textarea>`:`<input id="${path}" data-bind="${path}" value="${esc(text)}">`}</div>`;}
function imageKey(preset=salesman.preset,gender=salesman.appearance.gender){return personaImageMap[preset]?.[gender]||'alex';}
/* Natural language parser */
function parseDescription(text){const t=text.toLowerCase();let key=salesman.preset;
 if(/華爾街|wolf of wall street|激情銷售|強勢成交|超級業務|\bcloser\b|high[- ]energy sales/.test(t))key='wolf';
 else if(/analytical|分析|數據|data[- ]driven|冷靜/.test(t))key='strategist';
 else if(/luxury|高端|精品|奢華/.test(t))key='luxury';
 else if(/warm|溫暖|empathetic|同理|consultative|顧問/.test(t))key='advisor';
 else if(/professional|專業|沉穩|calm|expert/.test(t))key='expert';
 else if(/energetic|激情|高能量|陽光|friendly/.test(t))key='energetic';
 applyPreset(key);const p=salesman.personality;
 const hasPositive=(words)=>words.some(word=>{const re=new RegExp(word,'gi');let m;while((m=re.exec(t))){const before=t.slice(Math.max(0,m.index-24),m.index);if(!/(?:not|never|no|without|don't|do not|不|不要|避免)\s*(?:be\s+|very\s+|too\s+|要|太|過於|非常)?$/.test(before))return true;}return false;});
 if(hasPositive(['confident','自信']))p.confidence=Math.max(95,p.confidence);
 if(hasPositive(['aggressive','強勢','積極']))p.aggressiveness=Math.max(82,p.aggressiveness);
 if(hasPositive(['energetic','激情','高能量']))p.energy=Math.max(95,p.energy);
 if(hasPositive(['warm','溫暖','同理']))p.empathy=Math.max(92,p.empathy);
 if(/never pressure|never pressures|without pressure|no pressure|not aggressive|不強迫|不施壓|不要強勢|(?:不|別|避免|絕不).{0,6}施壓/.test(t)){p.aggressiveness=18;p.urgency=15;p.patience=Math.max(90,p.patience);salesman.sales.rules=salesman.sales.rules.filter(r=>r!=='urgency');}
 if(/\bfemale\b|女/.test(t))salesman.appearance.gender='female';else if(/\bmale\b|男/.test(t))salesman.appearance.gender='male';
 if(salesman.appearance.gender!==PRESETS[key].gender){salesman.identity.name=salesman.appearance.gender==='female'?'Emma Carter':'Marcus Reed';salesman.voice.name=salesman.appearance.gender==='female'?(key==='energetic'?'Emily':'Sophia'):'Marcus';}
 if(/roi/.test(t)&&!salesman.sales.rules.includes('roi'))salesman.sales.rules.push('roi');if(/book\s*(a\s*)?demo|預約\s*demo/i.test(t)){salesman.sales.goal='book_demo';salesman.sales.cta=GOALS.book_demo;}
 if(/white shirt|白襯衫/.test(t))salesman.appearance.outfit='white_shirt';if(/fast|快速/.test(t))salesman.voice.speed='fast';if(/slow|緩慢|慢速/.test(t))salesman.voice.speed='slow';
 const age=t.match(/(?:age[d]?\s*|around\s*|約\s*)(\d{2})/i)||t.match(/(\d{2})\s*(?:歲|years old)/);if(age)salesman.appearance.age=Math.max(25,Math.min(55,Number(age[1])));
 return key;
}
/* Persona generator & mock AI generation — future service boundaries */
function buildOutputContract(){const p=PRESETS[salesman.preset];return {identity:{...clone(salesman.identity),summary:p.summary},visual:{...clone(salesman.appearance)},personality:clone(salesman.personality),voice:{name:salesman.voice.name,speed:salesman.voice.speed,tone:salesman.voice.tone,conversation_style:salesman.voice.conversationStyle},sales_strategy:{methods:clone(salesman.sales.methods),rules:salesman.sales.rules.map(k=>RULES[k]),custom:salesman.sales.custom,discovery:p.discovery,pitch:p.pitch,closing:p.closing},product:{name:salesman.product.name,description:salesman.product.description,price:salesman.product.price,target_customer:salesman.product.targetCustomer,benefits:clone(salesman.product.benefits),features:clone(salesman.product.features),competitors:clone(salesman.product.competitors),promotions:clone(salesman.product.promotions),restrictions:clone(salesman.product.restrictions)},objections:clone(salesman.objections),goal:{type:salesman.sales.goal,cta:salesman.sales.cta},conversation:{opening_line:openingLine(),sample_questions:['What are you trying to solve?','How are you doing this today?','What does this cost your team?'],sample_pitch:p.pitch,sample_objection:salesman.objections[0]?.strategy||'',sample_close:p.closing}};}
/* Product knowledge */
/* Objection handler */
/* Website widget */
/* Mock conversation flow: replace this adapter with an agent later */
/* Conversion / CRM boundary: local-only simulated capture */
/* Voice adapter — optional native speech recognition, no TTS */

/* V2 State migration: keep V1 training and saved work, add shared preview state. */
function defaultState(){const s=defaultStateV1();s.revision=2;s.product=clone(DEFAULT_PRODUCT_ZH);s.objections=clone(DEFAULT_OBJECTIONS_ZH);s.sales.cta=GOALS.book_demo;s.appearance.variant=0;s.meta.previewMode='avatar';s.avatar={state:'idle',transcript:'',subtitle:'先不要急著看產品。我先問你一個問題。你現在這個問題，每個月到底正在花你多少錢？'};return s;}
function loadState(){const s=loadStateV1();let old;try{old=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');}catch{}if(old&&!old.revision){s.meta.generated=false;if(old.product?.description==='AI customer service platform that helps companies automate repetitive support questions.')s.product=clone(DEFAULT_PRODUCT_ZH);if(old.objections?.[0]?.objection==="It's too expensive.")s.objections=clone(DEFAULT_OBJECTIONS_ZH);if(['Book a Demo','Purchase','Leave Contact','Request Quote','Start Free Trial','Call Sales','Talk to Human'].includes(s.sales.cta))s.sales.cta=GOALS[s.sales.goal];}s.revision=2;s.meta.previewMode=['avatar','chat'].includes(s.meta.previewMode)?s.meta.previewMode:'avatar';s.avatar.state='idle';s.avatar.transcript='';s.avatar.subtitle=s.avatar.subtitle||PRESETS[s.preset].opening;s.appearance.variant=[0,1].includes(s.appearance.variant)?s.appearance.variant:0;s.chat.busy=false;s.chat.open=false;return s;}
function persist(){try{const snapshot=clone(salesman);snapshot.chat.busy=false;snapshot.chat.open=false;snapshot.avatar.state='idle';snapshot.avatar.transcript='';localStorage.setItem(STORAGE_KEY,JSON.stringify(snapshot));storageAvailable=true;$('#save-status').textContent='● 已儲存在此裝置';return true;}catch{storageAvailable=false;$('#save-status').textContent='無法儲存在此裝置';return false;}}
function scheduleSave(){clearTimeout(saveTimer);$('#save-status').textContent='儲存中…';saveTimer=setTimeout(persist,250);}
function markChanged(){salesman.meta.generated=false;renderPreview();scheduleSave();}
function priceLabel(){return numberPrice()===null?'專屬報價':money(numberPrice());}
function firstName(){return salesman.identity.name.trim().split(/\s+/)[0]||'Alex';}
/* Generated offline image sheets: two distinct portraits per persona. */
function portraitSpec(key=salesman.preset,variant=salesman.appearance.variant){const source=PORTRAIT_SHEETS[key];return {source:source||IMAGE_ASSETS[imageKey(key,PRESETS[key].gender)],panel:source?(variant===1?1:0):0,split:!!source};}
function currentImage(){return portraitSpec().source;}
function portraitHTML(key=salesman.preset,variant=salesman.appearance.variant,alt='原創虛構 AI 業務形象'){const p=portraitSpec(key,variant);return `<div class="portrait-thumb" style="--portrait-width:${p.split?'200%':'100%'};--portrait-left:${p.panel===1?'-100%':'0%'}"><img class="portrait-strip" src="${p.source}" alt="${esc(alt)}" decoding="async"></div>`;}
function bestVariant(appearance=salesman.appearance,key=salesman.preset){const weights={gender:8,style:3,outfit:4,environment:3,energy:2};const list=VARIANT_META[key];let best=0,score=-Infinity;list.forEach((v,i)=>{let n=-Math.abs(v.age-appearance.age)/8;for(const [field,weight] of Object.entries(weights))if(v[field]===appearance[field])n+=weight;if(n>score){score=n;best=i;}});return best;}
function mockGenerateImage(){const chosen=bestVariant();salesman.appearance.variant=chosen;return portraitSpec(salesman.preset,chosen);}
function renderVariants(){const host=$('#appearance-variants');if(!host)return;host.innerHTML=VARIANT_META[salesman.preset].map((v,i)=>`<button class="variant-choice ${i===salesman.appearance.variant?'active':''}" data-variant="${i}" aria-pressed="${i===salesman.appearance.variant}">${portraitHTML(salesman.preset,i,v.label)}<span>${esc(v.label)}</span></button>`).join('');}
/* Builder rendering retains all V1 training controls. */
function renderNav(){const nav=[['Overview','總覽','grid'],['Salesmen','AI 業務','user'],['Knowledge','產品知識','book'],['Playbooks','銷售腳本','flow'],['Conversations','對話紀錄','chat'],['Analytics','數據分析','chart'],['Integrations','整合','link'],['Settings','設定','settings']];$('#navigation').innerHTML=nav.map(([key,label,ico])=>`<button class="nav-item ${key==='Salesmen'?'active':''}" data-nav="${key}">${icon(ico)}<span>${label}</span>${key==='Salesmen'?'<span class="nav-count">1</span>':''}</button>${key==='Salesmen'?`<div class="subnav"><button data-nav="Salesmen"><span class="dot"></span><span id="sidebar-name">${esc(salesman.identity.name)}</span></button><button id="new-salesman">＋ 新增 AI 業務</button></div>`:''}`).join('');}
function renderPersonas(){$('#persona-grid').innerHTML=Object.entries(PRESETS).map(([key,p])=>`<button class="persona-card ${key===salesman.preset?'selected':''}" data-persona="${key}" aria-pressed="${key===salesman.preset}"><div class="persona-cover">${portraitHTML(key,0,p.zh+'預設形象')}${key===salesman.preset?'<span class="persona-selected">✓</span>':''}</div><div class="persona-copy"><h3>${p.emoji} ${esc(p.label)}</h3><p>${esc(p.zh)}</p><div class="traits">${p.traits.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="persona-description">${esc(p.short)}</div></div></button>`).join('');}
function renderSettings(){$('#description').value=salesman.description;$('#appearance-fields').innerHTML=textField('業務姓名','identity.name')+`<div class="grid2">${selectField('性別','appearance.gender',['male','female'])}${selectField('商務形象','appearance.style',['wall_street','executive','modern_saas','luxury','casual','tech_founder','professional_expert'])}</div><div class="slider-row"><label for="appearance.age">年齡 <output id="age-output">${salesman.appearance.age}</output></label><input type="range" id="appearance.age" data-bind="appearance.age" min="25" max="55" value="${salesman.appearance.age}"><div class="slider-labels"><span>25 歲</span><span>55 歲</span></div></div><div class="grid2">${selectField('服裝','appearance.outfit',['white_shirt','dark_suit','navy_suit','business_casual','turtleneck'])}${selectField('環境','appearance.environment',['luxury_office','modern_office','bright_office','dark_executive_office','studio','luxury_showroom'])}</div>${selectField('肢體能量','appearance.energy',['calm','balanced','energetic','intense'])}<div class="variant-strip" id="appearance-variants"></div>`;$('#appearance-description').value=salesman.appearance.image_description;renderVariants();$('#personality-fields').innerHTML=TRAIT_KEYS.map(k=>`<div class="slider-row"><label for="trait-${k}">${title(k)} <output id="out-${k}">${salesman.personality[k]}</output></label><input id="trait-${k}" type="range" data-bind="personality.${k}" min="0" max="100" value="${salesman.personality[k]}"></div>`).join('')+'<div class="slider-labels"><span>較保留</span><span>較強烈</span></div>';
$('#voice-fields').innerHTML=selectField('聲音角色','voice.name',[['Marcus','Marcus · 低沉 / 自信'],['Ethan','Ethan · 活力 / 快速'],['James','James · 專業 / 沉穩'],['Sophia','Sophia · 溫暖 / 親切'],['Olivia','Olivia · 精品 / 優雅'],['Emily','Emily · 明亮 / 活潑']])+`<div class="grid2">${selectField('說話速度','voice.speed',['slow','normal','fast'])}${selectField('語氣','voice.tone',['calm','professional','energetic','persuasive','elegant'])}</div>`+selectField('表達方式','voice.conversationStyle',['short_direct','balanced','detailed']);
$('#sales-methods').innerHTML=Object.entries(METHODS).map(([k,v])=>`<label><input type="checkbox" data-list="sales.methods" value="${k}" ${salesman.sales.methods.includes(k)?'checked':''}>${esc(v)}</label>`).join('');$('#sales-rules').innerHTML=Object.entries(RULES).map(([k,v])=>`<label><input type="checkbox" data-list="sales.rules" value="${k}" ${salesman.sales.rules.includes(k)?'checked':''} ${['no_scarcity','honesty','disclose'].includes(k)?'disabled title="此業務始終遵守這項原則"':''}>${esc(v)}</label>`).join('');$('#custom-method').value=salesman.sales.custom;}
function renderProduct(){$('#product-fields').innerHTML=textField('產品名稱','product.name')+textField('產品說明','product.description',true)+`<div class="grid2">${textField('價格','product.price')}${textField('目標客群','product.targetCustomer')}</div>`+['features','competitors','promotions','restrictions'].map(k=>textField(title(k)+' · 每行一項','product.'+k,true)).join('');renderBenefits();$('#website-url').value=salesman.knowledge.url;renderImports();}
function renderBenefits(){$('#benefit-tags').innerHTML=salesman.product.benefits.map((b,i)=>`<span class="tag">${esc(b)}<button data-remove-benefit="${i}" aria-label="移除 ${esc(b)}">×</button></span>`).join('')+'<input id="benefit-input" placeholder="新增一項優勢…" maxlength="100" aria-label="新增產品優勢">';}
function renderImports(){$('#website-import-result').innerHTML=salesman.knowledge.imported?'<div class="import-result">✓ 找到 23 個頁面<br>✓ 整理出 126 個產品資訊<br><small>範例知識 · 模擬匯入結果</small></div>':'';$('#upload-list').innerHTML=salesman.knowledge.files.map((f,i)=>`<div class="upload-item"><div>${esc(f.name)}<div><small>模擬擷取 ${Number(f.facts)||0} 項知識</small></div></div><button class="icon-btn" data-remove-file="${i}" aria-label="移除 ${esc(f.name)}">×</button></div>`).join('');}
function renderObjections(){$('#objection-list').innerHTML=salesman.objections.map((o,i)=>`<article class="objection-card"><label for="obj-${i}-objection">客戶說</label><div class="row"><input id="obj-${i}-objection" value="${esc(o.objection)}" data-objection="${i}" data-key="objection" placeholder="客戶的疑慮"><button class="icon-btn" data-remove-objection="${i}" aria-label="移除這個異議">×</button></div>${[['strategy','應對策略'],['never','不要'],['response_style','語氣']].map(([k,t])=>`<label for="obj-${i}-${k}">${t}</label>${k==='strategy'?`<textarea id="obj-${i}-${k}" data-objection="${i}" data-key="${k}">${esc(o[k])}</textarea>`:`<input id="obj-${i}-${k}" data-objection="${i}" data-key="${k}" value="${esc(o[k])}">`}`).join('')}</article>`).join('');}
function renderGoals(){$('#goal-options').innerHTML=Object.entries(GOALS).map(([k,v])=>`<label class="goal-option"><input type="radio" name="goal" value="${k}" ${salesman.sales.goal===k?'checked':''}>${v}</label>`).join('');$('#primary-cta').value=salesman.sales.cta;}
function openingLine(){if(salesman.product.name==='Customer Service AI')return PRESETS[salesman.preset].opening;const name=salesman.product.name||'這個產品';const lines={wolf:`先不要急著看 ${name}。我先問你一件事：你現在這個問題，每個月到底正在花你多少錢？`,advisor:`在推薦 ${name} 前，我想先了解：你最希望改善什麼？怎麼樣才算真的適合你？`,strategist:`我們先定義評估 ${name} 的指標。你希望改善成本、時間，還是其他可量化的結果？`,luxury:`關於 ${name}，你最重視什麼樣的體驗與標準？讓我先了解你的偏好。`,energetic:`一起看看 ${name} 能幫上什麼忙！你最想讓哪件事變得更輕鬆？`,expert:`評估 ${name} 前，我建議先釐清目前的做法，以及導入必須滿足的條件。你想先從哪裡開始？`};return lines[salesman.preset];}
function readiness(){return [{name:'人格已設定',done:!!salesman.identity.name.trim()&&!!PRESETS[salesman.preset],weight:20},{name:'產品知識已加入',done:!!salesman.product.name.trim()&&!!salesman.product.description.trim(),weight:25},{name:'成交目標已設定',done:!!GOALS[salesman.sales.goal]&&!!salesman.sales.cta.trim(),weight:15},{name:'異議處理已準備',done:salesman.objections.some(o=>o.objection.trim()&&o.strategy.trim()),weight:20},{name:'聲音已設定',done:!!salesman.voice.name&&['slow','normal','fast'].includes(salesman.voice.speed),weight:10},{name:'預覽已準備',done:!!currentImage(),weight:10}];}
function readinessScore(){return readiness().reduce((sum,item)=>sum+(item.done?item.weight:0),0);}
function trainingStatus(){return salesman.meta.generated&&readinessScore()===100?'已準備好開始銷售':'草稿';}
/* Preview composition: large avatar or full-height text, never profile-card stacking. */
function modeButtons(){return `<div class="mode-switch" role="group" aria-label="切換預覽模式"><button data-preview-mode="avatar" aria-pressed="${salesman.meta.previewMode==='avatar'}" class="${salesman.meta.previewMode==='avatar'?'active':''}">${icon('mic')}真人語音</button><button data-preview-mode="chat" aria-pressed="${salesman.meta.previewMode==='chat'}" class="${salesman.meta.previewMode==='chat'?'active':''}">${icon('chat')}文字對話</button></div>`;}
function renderPreviewMode(){const mode=salesman.meta.previewMode;$$('[data-preview-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.previewMode===mode);b.setAttribute('aria-pressed',b.dataset.previewMode===mode);});for(const scope of ['main','website']){$('#'+scope+'-avatar').hidden=mode!=='avatar';$('#'+scope+'-chat').hidden=mode!=='chat';}$('#website-widget').hidden=!UI_STATE.websiteWidgetOpen;$('#website-launcher').hidden=UI_STATE.websiteWidgetOpen;renderAvatarState();}
function renderAvatarPreview(){const p=PRESETS[salesman.preset],first=firstName(),ready=salesman.meta.generated&&readinessScore()===100;for(const scope of ['main','website']){const host=$('#'+scope+'-avatar');const signature=JSON.stringify([salesman.preset,salesman.appearance.variant,salesman.identity.name,ready]);if(host.dataset.renderKey===signature)continue;host.dataset.renderKey=signature;host.innerHTML=`<div class="avatar-portrait">${portraitHTML(salesman.preset,salesman.appearance.variant,p.zh+'原創虛構業務')}</div><div class="avatar-light"></div><div class="avatar-top"><div><div class="avatar-type">AI SALESMAN · ${esc(p.label.toUpperCase())}</div><h2 class="avatar-name">${esc(salesman.identity.name||'你的新業務')}</h2><div class="avatar-role">${esc(p.zh)}<br>${esc(p.role)}</div></div><span class="avatar-badge ${ready?'is-ready':''}"><span class="dot"></span>${ready?'訓練完成':'草稿'}</span></div><div class="avatar-middle">${ready?'':`<span class="draft-note">✦ 預覽模式 · 尚未完成訓練</span>`}</div><div class="avatar-bottom"><div class="avatar-status-row"><span class="avatar-state-dot"></span><span data-avatar-status role="status" aria-live="polite"></span></div><div class="call-wave" aria-hidden="true">${Array.from({length:28},(_,i)=>`<i style="--wave-height:${5+(i*13)%21}px;animation-delay:${(i*7%13)/10}s;animation-duration:${.4+(i%5)/10}s"></i>`).join('')}</div><div class="avatar-transcript" data-avatar-transcript></div><div class="subtitle-box"><p class="avatar-subtitle-text" data-avatar-subtitle></p></div><div class="avatar-quick" data-avatar-quick></div><div data-fallback-wrap ${UI_STATE.fallbackOpen?'':'hidden'}><p class="fallback-notice">無法使用麥克風時，可輸入一句話繼續真人演示。</p><form class="fallback-form" data-voice-form="${scope}"><label for="${scope}-voice-input" hidden>輸入想對業務說的話</label><input id="${scope}-voice-input" placeholder="例如：499 美金有點貴" maxlength="1500"><button class="btn primary small" aria-label="送出文字並演示回答">送出</button></form></div><div class="avatar-controls"><button class="call-mic" data-start-voice>${icon('mic')}<span data-mic-label>開始說話</span></button><button class="call-control" data-preview-mode="chat">⌨ 切到文字</button><button class="call-control end" data-end-voice>× 結束</button></div><p class="avatar-disclosure">原創虛構 AI 業務 · 動態與配音為字幕模擬，未播放聲音</p></div>`;}renderAvatarState();}
function renderAvatarState(){if(!salesman.avatar)return;const state=salesman.avatar.state,first=firstName();const labels={idle:runtime.activeCall?`${first} 正在線上`:`${first} 正在線上`,listening:'正在聽你說…',thinking:`${first} 正在思考…`,speaking:`${first} 正在回答 · 字幕演示`};$$('.avatar-screen').forEach(root=>{root.dataset.state=state;const statusNode=root.querySelector('[data-avatar-status]');if(statusNode&&statusNode.textContent!==(labels[state]||labels.idle))statusNode.textContent=labels[state]||labels.idle;const subtitle=root.querySelector('[data-avatar-subtitle]');if(subtitle)subtitle.textContent=salesman.avatar.subtitle||openingLine();const transcript=root.querySelector('[data-avatar-transcript]');if(transcript)transcript.textContent=salesman.avatar.transcript?'你：「'+salesman.avatar.transcript+'」':'';const label=root.querySelector('[data-mic-label]');if(label)label.textContent=state==='listening'?'停止聆聽':runtime.activeCall?'繼續說話':'開始說話';const quick=root.querySelector('[data-avatar-quick]');if(quick){const options=salesman.chat.messages.length?salesman.chat.quick:defaultQuick();const content=salesman.chat.busy?'':options.filter(Boolean).slice(0,4).map(q=>`<button data-quick="${esc(q)}">${esc(q)}</button>`).join('');if(quick.dataset.renderContent!==content){quick.innerHTML=content;quick.dataset.renderContent=content;}}const fallback=root.querySelector('[data-fallback-wrap]');if(fallback)fallback.hidden=!UI_STATE.fallbackOpen;});}
function renderChatPreview(){const p=PRESETS[salesman.preset];for(const scope of ['main','website']){$('#'+scope+'-chat-header').innerHTML=`${portraitHTML(salesman.preset,salesman.appearance.variant,'')}<div><h3>${esc(salesman.identity.name)}</h3><p>AI 銷售業務 · ${esc(p.zh)}</p></div><span class="status"><span class="dot"></span>在線</span>`;const log=$('#'+scope+'-messages');log.innerHTML=salesman.chat.messages.length?salesman.chat.messages.map((m,index)=>m.role==='roi'?renderROI(m.data,index,scope):`<div class="message-wrap ${m.role==='user'?'user-wrap':''}"><div class="message-author">${esc(m.role==='user'?'你':m.speaker||firstName())}</div><div class="message ${m.role==='user'?'user-message':''}">${esc(m.text)}</div></div>`).join(''):`<div class="conversation-empty">${esc(openingLine())}<br><br>先選一個話題，開始和 ${esc(firstName())} 對話。</div>`;log.innerHTML+=salesman.chat.busy?`<div class="typing">${esc(firstName())} 正在輸入… <i></i><i></i><i></i></div>`:`<div class="quick-replies" aria-label="快速回答">${(salesman.chat.messages.length?salesman.chat.quick:defaultQuick()).filter(Boolean).map(q=>`<button data-quick="${esc(q)}">${esc(q)}</button>`).join('')}</div>`;$('#'+scope+'-send').disabled=salesman.chat.busy;log.scrollTop=log.scrollHeight;}}
function renderChat(){renderChatPreview();renderAvatarState();}
function renderProfileDrawer(){const p=PRESETS[salesman.preset],score=readinessScore();$('#drawer-title').textContent=salesman.identity.name+' · 業務資料';$('#drawer-content').innerHTML=`<div class="preview-card"><span class="pill">${trainingStatus()}</span><h2 style="margin:13px 0 8px">${esc(p.label)}</h2><p class="summary-text">${esc(p.summary)}</p></div><div class="preview-card"><div class="row between"><strong>銷售準備度</strong><strong class="readiness-score" id="readiness-score">${score}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${score}%"></div></div><div class="readiness-list">${readiness().map(x=>`<span><b>${x.done?'✓':'○'}</b>${x.name}</span>`).join('')}</div><p class="drawer-note">${score===100?(salesman.meta.generated?'訓練完成，已準備好開始銷售。':'設定已完整。按「建立 AI Salesman」完成訓練。'):'還需要訓練：請補齊尚未完成的設定。'}</p></div><div class="preview-card"><span class="eyebrow">人格設定</span>${TRAIT_KEYS.map(k=>`<div class="trait-meter"><div class="row between"><span>${title(k)}</span><strong>${salesman.personality[k]}</strong></div><div class="progress-track"><div class="progress-fill" style="width:${salesman.personality[k]}%"></div></div></div>`).join('')}</div><div class="preview-card"><span class="eyebrow">業務檔案</span><dl class="profile-grid">${[['員工類型','AI Salesman'],['角色',p.role],['銷售方式',salesman.sales.methods.map(m=>METHODS[m]).join(' + ')],['成交目標',salesman.sales.cta],['聲音',salesman.voice.name+' · '+title(salesman.voice.speed)],['語氣',title(salesman.voice.tone)],['目標客群',salesman.product.targetCustomer],['形象',title(salesman.appearance.gender)+' · '+salesman.appearance.age+' 歲'],['服裝',title(salesman.appearance.outfit)],['環境',title(salesman.appearance.environment)]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></div><div class="preview-card"><span class="eyebrow">開場白</span><p class="opening-quote">${esc(openingLine())}</p></div><div class="preview-card"><span class="eyebrow">${esc(firstName())} 的銷售流程</span><div class="playbook-steps">${[['探索需求',p.discovery],['量化問題','以真實資料與明確假設評估成本、時間和風險。'],['建立價值',p.pitch],['處理異議',salesman.objections[0]?.strategy||'請加入異議策略。'],['推進下一步',p.closing]].map(([t,d],i)=>`<div class="playbook-step"><b>0${i+1}</b><strong>${t}</strong><p>${esc(d)}</p></div>`).join('')}</div></div><p class="drawer-note">預覽採用原創虛構人物與預先準備的影像變體。外貌設定會挑選最接近的素材，不會即時生成圖片。</p><button class="btn full" id="image-credits" style="margin-top:15px">關於 Demo 與人物素材</button>`;}
function renderWebsite(){const p=salesman.product;$('#website-brand').textContent='✳ '+(p.name||'你的產品');$('#website-headline').textContent=p.name==='Customer Service AI'?'讓每一個提問，都得到即時回應。':(p.name||'你的產品')+'，讓下一步更有可能。';$('#website-description').textContent=p.description||'加入你的產品說明，讓 AI 業務開始學習。';$('#website-price').textContent=priceLabel();$('#context-plan').textContent=salesman.chat.plan;let host='yourcompany.com';try{if(salesman.knowledge.url)host=new URL(salesman.knowledge.url).hostname;}catch{}$('#browser-url').textContent=host+'/pricing';$('#website-shell').classList.toggle('mobile-mode',salesman.meta.device==='mobile');$$('[data-device]').forEach(b=>{b.classList.toggle('active',b.dataset.device===salesman.meta.device);b.setAttribute('aria-pressed',b.dataset.device===salesman.meta.device);});$('#website-launcher').innerHTML=portraitHTML(salesman.preset,salesman.appearance.variant,firstName())+`<div><h3>${esc(firstName())} <span class="dot"></span></h3><p>AI 銷售業務 · 在線</p><strong>${UI_STATE.websiteEntry==='avatar'?'和 '+esc(firstName())+' 語音對話 →':'開始文字對話 →'}</strong></div>`;$$('[data-website-entry]').forEach(b=>{b.classList.toggle('active',b.dataset.websiteEntry===UI_STATE.websiteEntry);b.setAttribute('aria-pressed',b.dataset.websiteEntry===UI_STATE.websiteEntry);});}
function renderPreview(){$('#crumb-name').textContent=salesman.identity.name||'新的 AI 業務';if($('#sidebar-name'))$('#sidebar-name').textContent=salesman.identity.name;$('#appearance-summary').textContent=title(salesman.appearance.gender)+' · '+salesman.appearance.age+' 歲';$('#personality-summary').textContent='自信 '+salesman.personality.confidence;$('#voice-summary').textContent=salesman.voice.name+' · '+title(salesman.voice.speed);$('#behavior-summary').textContent=salesman.sales.methods.length+' 種方法';renderAvatarPreview();renderChatPreview();renderProfileDrawer();renderWebsite();renderPreviewMode();}
function renderAll(){renderNav();renderPersonas();renderSettings();renderProduct();renderObjections();renderGoals();renderPreview();}
/* Persona selection and training lifecycle. */
function applyPreset(key,{resetChat=true}={}){const p=PRESETS[key];stopVoiceConversation({silent:true});salesman.preset=key;salesman.identity={name:p.name,archetype:p.label,title:p.subtitle};salesman.appearance={gender:p.gender,age:p.age,style:p.style,outfit:p.outfit,environment:p.environment,energy:p.energy,image_description:p.image_description,image_variant:0,image_override:'',variant:0};salesman.personality=Object.assign(Object.fromEntries(TRAIT_KEYS.map((k,i)=>[k,p.values[i]])),p.extras);salesman.voice={name:p.voice[0],speed:p.voice[1],tone:p.voice[2],conversationStyle:p.voice[3]};salesman.sales.methods=clone(p.methods);salesman.sales.rules=Object.keys(RULES).filter(r=>r!=='urgency'||['wolf','energetic'].includes(key));salesman.meta.generated=false;salesman.avatar.subtitle=p.opening;salesman.avatar.transcript='';if(resetChat)resetConversation();}
function mockGeneratePersona(){const p=salesman.personality,a=salesman.appearance;let key=salesman.preset;if(a.style==='luxury')key='luxury';else if(p.confidence>85&&p.aggressiveness>70&&p.energy>80)key='wolf';else if(p.energy>85&&p.empathy>65)key='energetic';else if(p.empathy>90&&p.patience>80)key='advisor';else if(p.aggressiveness<45&&p.directness>=75&&/analytical|分析|數據|data/.test(salesman.description.toLowerCase()))key='strategist';else if(a.age>40&&p.patience>80&&p.aggressiveness<30)key='expert';salesman.preset=key;salesman.identity.archetype=PRESETS[key].label;salesman.identity.title=PRESETS[key].subtitle;salesman.appearance.variant=bestVariant();salesman.meta.generated=readinessScore()===100;return buildOutputContract();}
async function mockLoading(lines,titleText){if(generationBusy)return false;generationBusy=true;$('#loading-title').textContent=titleText;$('#loading-dialog').showModal();try{for(let i=0;i<lines.length;i++){$('#loading-steps').innerHTML=lines.map((line,j)=>`<div class="${j<i?'done':j===i?'doing':''}">${j<i?'✓':j===i?'✦':'○'} &nbsp;${esc(line)}</div>`).join('');await sleep(370);}return true;}finally{$('#loading-dialog').close();generationBusy=false;}}
async function generateSalesman(){if(readinessScore()!==100){toast('請先補齊姓名、產品知識、異議策略、聲音與成交目標。');$('#profile-drawer').showModal();return;}stopVoiceConversation({silent:true});if(!await mockLoading(['正在理解你的銷售風格…','正在建立人格…','正在整理產品知識…','正在建立異議處理策略…','正在訓練銷售流程…','正在準備真人形象…'],'你的新業務，即將上線。'))return;mockGeneratePersona();salesman.meta.previewMode='avatar';resetConversation();runtime.activeCall=true;salesman.avatar.subtitle='';const welcome={role:'assistant',speaker:firstName(),text:openingLine()};salesman.chat.messages.push(welcome);salesman.chat.quick=defaultQuick();renderPersonas();renderPreview();$('#main-avatar').classList.remove('stage-enter');void $('#main-avatar').offsetWidth;$('#main-avatar').classList.add('stage-enter');$('#live-preview').scrollIntoView({behavior:'smooth',block:'nearest'});persist();toast(salesman.identity.name+' 已完成訓練，準備開始銷售。');await playAvatarResponse(welcome.text);}
/* Product knowledge import remains local and explicitly simulated. */
async function mockImportWebsite(){const field=$('#website-url');let url;try{url=new URL(field.value);if(!['http:','https:'].includes(url.protocol))throw Error();}catch{field.focus();toast('請輸入完整網址，例如 https://yourcompany.com。');return;}const button=$('#import-website');button.disabled=true;button.textContent='正在閱讀網站…';await sleep(1200);salesman.knowledge.url=url.href;salesman.knowledge.imported=true;renderImports();markChanged();button.disabled=false;button.textContent='讀取網站';toast('模擬匯入完成：23 個頁面、126 個產品資訊。');}
function mockUploadFiles(files){const valid=Array.from(files).filter(f=>/\.(pdf|ppt|pptx|docx|txt)$/i.test(f.name)&&f.size<=20*1024*1024);if(valid.length!==files.length)toast('支援 20 MB 以內的 PDF、PPT、DOCX、TXT。');for(const f of valid){if(salesman.knowledge.files.some(x=>x.name===f.name))continue;salesman.knowledge.files.push({name:f.name,size:f.size,facts:/ppt/i.test(f.name)?78:24});}renderImports();markChanged();if(valid.length)toast('知識已加入。此 Demo 的知識擷取為模擬結果。');}
/* Shared sales conversation: persona-specific discovery through close. */
function defaultQuick(){return salesman.product.name==='Customer Service AI'?['降低客服成本','提升回覆速度','我覺得太貴']:['了解產品是否適合','比較方案','我覺得太貴'];}
function resetConversation(){stopVoiceConversation({silent:true});salesman.chat.messages=[];salesman.chat.quick=defaultQuick();salesman.chat.stage='discovery';salesman.chat.team=32;salesman.chat.busy=false;salesman.avatar.subtitle=openingLine();salesman.avatar.transcript='';}
function ensureConversation(){if(salesman.chat.messages.length)return;salesman.chat.messages.push({role:'assistant',speaker:firstName(),text:'我是 '+firstName()+'，你的 AI 銷售業務。'+openingLine()});salesman.chat.quick=defaultQuick();}
function latestROI(){return [...salesman.chat.messages].reverse().find(m=>m.role==='roi'&&m.data&&m.data.price===numberPrice())?.data||null;}
function personaLine(lines){return lines[salesman.preset]||lines.expert;}
function mockObjection(text){const t=text.toLowerCase(),r=latestROI(),s=r?r.team*r.cost*r.rate/100:null,price=numberPrice(),priceText=salesman.product.price||'目前的月費',roiText=s!==null?`剛才的假設估算顯示，每月可能釋放 ${money(s)} 的營運容量`:'我們還沒有驗證你的成本與可自動化比例';
 if(/expensive|too much|價格|太貴|有點貴|很貴|昂貴|price|預算/.test(t))return {text:personaLine({wolf:r?`我懂。但先別只看 ${priceText}。\n\n${roiText}。這不是保證節省，而是一個值得驗證的商業問題。\n\n下一步：用你的真實數字，看看這筆投資成不成立。`:`我懂。但先別急著談 ${priceText}。\n\n你現在這個問題，每個月到底正在花你多少錢？\n\n先把這筆帳算清楚，再決定值不值得。`,advisor:'可以理解。我想先確認一下：你比較擔心的是每月預算，還是目前還不確定這套方案能不能真的帶來足夠價值？\n\n我們可以慢慢把疑慮釐清，不必急著決定。',strategist:r?`我們先用數字看。\n\n${roiText}。以 ${priceText} 計算，價值／成本約為 ${price>0?(s/price).toFixed(1)+' 倍':'尚無法計算'}。\n\n真正需要驗證的是：這個自動化比例是否符合你的實際流程。`:`我們先用數字看。月費是 ${priceText}，但還缺兩個變數：目前成本，以及可自動化比例。\n\n先建立基準，再判斷是否值得。`,luxury:'我想先了解的，是你期待這個方案帶來什麼樣的體驗與結果。\n\n如果價值不符合你的標準，我不會建議你選擇它。',energetic:'我懂！我們可以很快算出它到底值不值得。\n\n先從你的團隊開始：目前大概有多少客服人員？一起把這件事變清楚！',expert:'這是一個合理的問題。我建議不要單看月費。\n\n先確認三件事：現在的成本、可以自動化的比例，以及導入風險。\n\n條件確認完，再決定是否值得。'}),quick:salesman.preset==='energetic'?['1–5','6–20','21–50','50+']:['計算 ROI','比較方案',salesman.sales.cta],stage:salesman.preset==='energetic'?'team':'objection'};
 if(/think|consider|考慮|想想/.test(t))return {text:personaLine({wolf:'可以。但我們先把真正卡住的地方找出來。\n\n是價格、導入，還是不確定到底能不能幫到你？',advisor:'當然，你可以保留考慮的空間。還有哪一點讓你不太放心？我可以先把資訊補齊。',strategist:'我們可以把未確定的項目列出來：成本、實際效果、導入條件。你認為哪一項還缺乏證據？',luxury:'不必倉促決定。哪個細節尚未符合你的期待？我會協助你確認到位。',energetic:'沒問題！要不要先抓出最讓你猶豫的一點？把它說清楚，下一步會容易很多。',expert:'保留評估時間很合理。我建議先列出尚未驗證的假設，而不是只憑感覺往下走。'}),quick:['價格','導入方式','會適合我們嗎？']};
 if(/another solution|already use|competitor|其他方案|其他系統|已經有|競品/.test(t))return {text:personaLine({wolf:'好，那我們有比較基準了。\n\n現有方案哪裡做得好？又有哪個問題一直沒解決？先找到差距，再談要不要換。',advisor:'了解。你對目前方案最滿意的是什麼？又希望哪裡能更好？不一定需要更換，我們先確認真正的需求。',strategist:'建議用相同標準比較：功能覆蓋、總成本、導入風險。你願意先說明現有方案的限制嗎？',luxury:'我想先了解，你對目前體驗有哪些期待尚未被滿足。唯有能提供實質提升，才值得考慮更換。',energetic:'那很好，我們可以直接比較！你現在最喜歡哪個功能？又有哪個地方希望更順手？',expert:'已有系統代表切換也有成本。先評估現有架構的限制，以及更換的必要性，再做判斷。'}),quick:['比較方案','導入方式',salesman.sales.cta]};
 const custom=salesman.objections.find(o=>o.objection.trim().length>2&&t.includes(o.objection.trim().toLowerCase()));if(custom)return {text:personaLine({wolf:'先把這件事說清楚。',advisor:'謝謝你說出這個顧慮。',strategist:'我們可以依這個方向驗證。',luxury:'這個細節值得確認。',energetic:'好，我們一起拆解看看！',expert:'這個問題需要具體評估。'})+'\n\n'+custom.strategy+'\n\n你最希望先確認哪一點？',quick:['了解產品是否適合',salesman.sales.cta]};return null;
}
function mockConversation(text){const t=text.trim().toLowerCase(),goal=salesman.sales.cta.trim()||GOALS[salesman.sales.goal],product=salesman.product;const replies=q=>q.filter(Boolean);
 if(t===goal.toLowerCase()||/^book (a )?demo$|^預約(?:\s*demo)?$/i.test(t))return {text:PRESETS[salesman.preset].closing,quick:[],action:'conversion',stage:'close'};
 if(/stop|not interested|leave me alone|不要再|沒興趣|不用了|先結束/.test(t))return {text:personaLine({wolf:'收到。我們就先到這裡。需要重新評估時，我在。',advisor:'好的，謝謝你和我聊聊。你可以按自己的步調探索。',strategist:'了解。先保留目前的評估資訊，需要時再繼續。',luxury:'當然。希望你能找到最合適的選擇。',energetic:'好！需要幫忙時，再找我就可以了。',expert:'了解。若未來條件改變，我們再重新評估。'}),quick:[],stage:'ended'};
 if(/are you.*(human|real|ai)|你是.*(真人|ai|機器)|你是真人|robot/.test(t))return {text:`我是 ${firstName()}，AI 銷售業務，不是真人。這是前端示範，人物動態、回答與字幕皆為模擬；我會依你設定的產品知識協助你探索方案。`,quick:['比較方案','看看就好']};
 const objection=mockObjection(t);if(objection)return objection;
 if(/降低客服成本|降低成本|減少成本|reduce support cost|提升回覆速度|加快|improve response time/.test(t))return {text:personaLine({wolf:'好。先別談功能。\n\n你目前有多少客服人員？我們先看問題的規模。',advisor:'我們先了解團隊的現況。現在大約有多少客服人員？哪類問題最占用他們的時間？',strategist:'先建立人力基準。你們目前有多少客服人員？這會影響我們後續估算的範圍。',luxury:'讓我先了解服務團隊的規模。目前有多少位同事在照顧客戶？',energetic:'這是很適合一起拆解的方向！先告訴我，你們大概有多少客服人員？',expert:'我們先確認現有資源。客服團隊目前大約有多少人？後續再評估哪些工作適合自動化。'}),quick:['1–5','6–20','21–50','50+'],stage:'team'};
 const range=/^(1[–-]5|6[–-]20|21[–-]50|50\+)$/.test(t),spoken=t.match(/(\d+)\s*(?:位|人|個客服)/),plain=salesman.chat.stage==='team'&&/^\d+$/.test(t);if(range||spoken||plain){const team=/^1[–-]5$/.test(t)?3:/^6[–-]20$/.test(t)?12:/^21[–-]50$/.test(t)?32:t==='50+'?60:Math.max(1,Math.min(10000,Number(spoken?spoken[1]:t)));return {text:personaLine({wolf:'這就有討論價值了。\n\n如果一部分重複問題可以自動處理，這些時間能值多少？\n\n我們直接算一筆帳。',advisor:'謝謝，這讓我比較了解你們的規模。我們可以用一個保守情境，看看能為團隊釋放多少時間，再決定是否值得繼續。',strategist:'已建立人力情境。下一步需要每位人員的月成本，以及可自動化比例。ROI 計算器可以讓你調整這兩項假設。',luxury:'我了解了。我們可以先評估哪些重複工作適合交給系統，讓團隊保留更多心力在有價值的客戶體驗上。',energetic:'收到！如果把重複工作減少一部分，團隊應該能輕鬆不少。我們用你可以調整的數字，看看可能帶來多少價值！',expert:'這個規模值得進一步評估。但自動化不等於直接減少現金支出，我們先估算可釋放的人力容量，再看實際效益。'}),quick:['計算 ROI','我覺得太貴','我再考慮'],stage:'roi',team};}
 if(/calculate roi|計算|roi|投報|投資報酬/.test(t))return {text:personaLine({wolf:'好，我們來算。\n\n下面都是可調整的假設，不是保證節省。把它換成你的真實數字，看看這件事值不值得往下走。',advisor:'我們一起看一個保守的估算。你可以修改人數、每人月成本及自動化比例，讓情境更接近你們的現況。',strategist:'計算式是：客服人數 × 每人月成本 × 自動化比例。\n\n價值／成本與淨 ROI 會同步更新。估算代表可釋放容量，仍需驗證可實現性。',luxury:'我們以可驗證的價值作為參考。這份估算是為了協助判斷是否符合你的標準，不取代實際的體驗評估。',energetic:'來看看數字！你可以直接調整下面的假設，馬上看到差異。這是估算，我們會再用實際流程驗證。',expert:'請把估算視為初步評估。它尚未扣除導入、人員訓練與維護成本，也不代表一定能轉成現金節省。'}),quick:replies(['我覺得太貴','我再考慮',goal]),roi:true,stage:'close'};
 if(/compare|比較|方案/.test(t)){const facts=`入門方案：US$99／月（示範方案）。\nPro：${product.price}（你設定的價格）。\n企業方案：專屬報價。`;return {text:personaLine({wolf:'先別被方案名稱帶走。你要的是解決問題。\n\n',advisor:'我先把選擇整理給你，我們再一起找合適的方案。\n\n',strategist:'先列出目前的價格基準。功能差異需要依產品知識進一步驗證。\n\n',luxury:'我會從你的需求與期待出發，協助你選擇。以下是目前方案。\n\n',energetic:'可以！先快速看一下三種選擇，再找最適合你的那個！\n\n',expert:'我們先比較已知資訊，再確認功能覆蓋與導入限制。\n\n'})+facts+'\n\n'+personaLine({wolf:'哪個問題，是你現在最需要解決的？',advisor:'你最在意的是預算、工作量，還是導入便利性？',strategist:'你希望用哪個指標作為主要比較標準？',luxury:'哪個方向最接近你期待的體驗？',energetic:'你最想先改善哪件事？',expert:'有哪些條件是你們不能妥協的？'}),quick:['降低客服成本','導入方式',goal]};}
 if(/implementation|導入|整合/.test(t))return {text:personaLine({wolf:'那就確認真正的門檻。你們現在用哪些系統？先把限制說清楚，我們才知道怎麼往下走。',advisor:'我們可以先整理你們目前的系統與工作習慣。哪個部分最讓你擔心？我不會在還沒確認前承諾導入時間。',strategist:'導入評估分成三項：資料來源、系統整合與權限要求。請先說明現有系統，我們才能驗證可行性。',luxury:'導入過程也應該符合你的服務標準。你希望保留哪些既有流程？我們先確認體驗不會因此受影響。',energetic:'我們把導入拆成幾個小步驟就容易多了！你們現在最常用哪套系統？先從這裡確認。',expert:'導入需要先確認資料品質、權限、既有系統與維護責任。在這些條件釐清之前，不應承諾時程或整合效果。'}),quick:['會適合我們嗎？',goal]};
 if(/will it work|fit|適合|效果|產品/.test(t))return {text:personaLine({wolf:'先確認這件事對你有沒有價值。\n\n',advisor:'先了解你最想改善的工作，再來判斷是否適合。\n\n',strategist:'我們用已知產品資訊對照你的需求。\n\n',luxury:'我會以你的標準衡量，而不只是列出功能。\n\n',energetic:'來找一個最貼近你團隊的使用情境！\n\n',expert:'先說清楚產品定位，再驗證限制與適用條件。\n\n'})+product.description+(product.benefits.length?'\n\n已設定的優勢：'+product.benefits.join('、')+'。':'')+'\n\n你最想先驗證哪一項？',quick:['計算 ROI','導入方式',goal]};
 if(/just exploring|看看|逛逛/.test(t))return {text:personaLine({wolf:'可以。先看看。想算清楚價值的時候，我們再聊。',advisor:'當然，慢慢看就好。如果需要，我可以陪你比較方案，不必急著做決定。',strategist:'了解。你可以先比較方案，再決定是否需要建立 ROI 情境。',luxury:'請慢慢探索。找到感興趣的方向時，我再為你做更精準的推薦。',energetic:'沒問題！先逛逛，看到有興趣的地方隨時找我！',expert:'了解。建議先保留需要驗證的問題，有需要再逐項討論。'}),quick:['比較方案','了解產品是否適合']};
 return {text:personaLine({wolf:'先讓我問你一件事：這個問題不解決，每個月的代價是什麼？',advisor:'我想先多了解你的情況。你最希望這個方案替你改善什麼？',strategist:'我們先定義問題與成功指標。你目前有哪個基準數字可以參考？',luxury:'讓我先了解你的期待。什麼樣的結果，才符合你心目中的標準？',energetic:'好！我們從最有感的地方開始。你最想讓哪件事變得更簡單？',expert:'我建議先確認目前的流程與限制。你現在遇到的主要瓶頸是什麼？'}),quick:['了解產品是否適合','計算 ROI',goal]};
}
/* Independent adapters: real services can replace these without changing the UI. */
const adapters={stt:mockSpeechToText,llm:mockConversation,tts:mockTextToSpeech,avatar:mockAvatarAnimation};
function speechToText(options={}){return adapters.stt(options);}
function generateSalesResponse(text){return Promise.resolve(adapters.llm(text,buildOutputContract()));}
function textToSpeech(text){return Promise.resolve(adapters.tts(text,salesman.voice));}
function animateAvatar(state){return adapters.avatar(state);}
function mockTextToSpeech(text,voice){return {kind:'subtitle-only',characterDelay:voice.speed==='fast'?27:voice.speed==='slow'?46:35,text};}
function mockAvatarAnimation(state){salesman.avatar.state=state;renderAvatarState();}
function setAvatarState(state){if(!['idle','listening','thinking','speaking'].includes(state))throw new Error('Invalid avatar state');animateAvatar(state);}
function abortRecognition(){const active=runtime.recognition,reject=runtime.recognitionReject;runtime.recognition=null;runtime.recognitionReject=null;runtime.voiceEpoch++;if(active){active.onresult=null;active.onerror=null;active.onend=null;try{active.abort();}catch{}}if(reject)reject(Object.assign(new Error('cancelled'),{code:'cancelled'}));}
function mockSpeechToText(){return new Promise((resolve,reject)=>{const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition){reject(Object.assign(new Error('unsupported'),{code:'unsupported'}));return;}abortRecognition();const rec=new SpeechRecognition(),epoch=runtime.voiceEpoch;runtime.recognition=rec;runtime.recognitionReject=reject;rec.lang='zh-TW';rec.interimResults=true;rec.continuous=false;let settled=false;const done=(value,error)=>{if(settled)return;settled=true;if(runtime.recognition===rec){runtime.recognition=null;runtime.recognitionReject=null;}try{rec.stop();}catch{}if(error)reject(error);else resolve(value);};rec.onresult=event=>{if(epoch!==runtime.voiceEpoch)return;let final='',partial='';for(let i=0;i<event.results.length;i++){if(event.results[i].isFinal)final+=event.results[i][0].transcript;else partial+=event.results[i][0].transcript;}salesman.avatar.transcript=final||partial;renderAvatarState();if(final.trim())done(final.trim());};rec.onerror=event=>done('',Object.assign(new Error(event.error),{code:event.error}));rec.onend=()=>{if(!settled)done('',Object.assign(new Error('no-speech'),{code:'no-speech'}));};try{rec.start();}catch{done('',Object.assign(new Error('unavailable'),{code:'unavailable'}));}});}
async function startVoiceConversation(){if(salesman.avatar.state==='listening'){abortRecognition();setAvatarState('idle');return;}runtime.revealEpoch++;runtime.responseEpoch++;salesman.chat.busy=false;runtime.activeCall=true;ensureConversation();salesman.avatar.subtitle='請說出你想解決的問題。';salesman.avatar.transcript='';setAvatarState('listening');try{const transcript=await speechToText();if(!transcript)return;UI_STATE.fallbackOpen=false;await sendMessage(transcript);}catch(error){if(error.code==='cancelled')return;setAvatarState('idle');UI_STATE.fallbackOpen=true;const message=error.code==='not-allowed'?'麥克風權限未開啟，你可以輸入文字或使用快速選項。':error.code==='no-speech'?'沒有收到語音。請再試一次，或輸入文字繼續。':'這個瀏覽器目前無法使用語音辨識，請輸入文字或使用快速選項。';salesman.avatar.subtitle=message;renderAvatarState();toast(message);}}
function stopVoiceConversation({silent=false}={}){abortRecognition();runtime.responseEpoch++;runtime.revealEpoch++;runtime.activeCall=false;if(salesman?.chat){salesman.chat.busy=false;if(!salesman.chat.quick.length&&salesman.chat.stage!=='ended')salesman.chat.quick=defaultQuick();}if(salesman?.avatar){salesman.avatar.state='idle';salesman.avatar.transcript='';if(!silent)salesman.avatar.subtitle='對話已結束。需要時，可以再繼續。';}if(!silent){renderChat();scheduleSave();toast('已結束本次語音演示，文字紀錄已保留。');}}
async function revealSubtitle(text,{characterDelay=35,epoch=runtime.revealEpoch}={}){const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;const chunks=[];let remaining=text.replace(/\n+/g,' ').trim();while(remaining.length){let length=Math.min(64,remaining.length);if(length<remaining.length){const near=remaining.slice(0,length);const cut=Math.max(near.lastIndexOf('。'),near.lastIndexOf('？'),near.lastIndexOf('！'));if(cut>18)length=cut+1;}chunks.push(remaining.slice(0,length));remaining=remaining.slice(length);}for(const chunk of chunks){if(epoch!==runtime.revealEpoch)return false;if(reduced){salesman.avatar.subtitle=chunk;renderAvatarState();await sleep(Math.max(900,chunk.length*25));}else{let partial='';for(const char of Array.from(chunk)){if(epoch!==runtime.revealEpoch)return false;partial+=char;salesman.avatar.subtitle=partial;renderAvatarState();await sleep(characterDelay);}await sleep(330);}}return epoch===runtime.revealEpoch;}
async function playAvatarResponse(text){const epoch=++runtime.revealEpoch;const playback=await textToSpeech(text);if(epoch!==runtime.revealEpoch)return;setAvatarState('speaking');const completed=await revealSubtitle(text,{characterDelay:playback.characterDelay||35,epoch});if(completed){setAvatarState('idle');scheduleSave();}}
async function sendMessage(text){text=String(text).trim();if(!text||salesman.chat.busy)return;abortRecognition();runtime.revealEpoch++;runtime.activeCall=true;ensureConversation();salesman.chat.messages.push({role:'user',text:text.slice(0,1500)});salesman.avatar.transcript=text.slice(0,1500);salesman.chat.busy=true;salesman.chat.quick=[];const epoch=++runtime.responseEpoch;$$('[data-chat-input],[data-voice-form] input').forEach(input=>input.value='');setAvatarState('thinking');renderChat();try{await sleep(700);if(epoch!==runtime.responseEpoch)return;const result=await generateSalesResponse(text);if(epoch!==runtime.responseEpoch)return;if(!result||typeof result.text!=='string')throw new Error('Invalid response');salesman.chat.busy=false;if(result.stage)salesman.chat.stage=result.stage;if(result.team)salesman.chat.team=result.team;salesman.chat.messages.push({role:'assistant',speaker:firstName(),text:result.text});if(result.roi)salesman.chat.messages.push({role:'roi',text:'模擬 ROI 估算',data:{team:salesman.chat.team,cost:500,rate:30,price:numberPrice(),product: salesman.product.name}});salesman.chat.quick=result.quick||[];renderChat();persist();if(result.action==='conversion'){setAvatarState('idle');salesman.avatar.subtitle=result.text;renderAvatarState();openConversion();}else await playAvatarResponse(result.text);}catch{if(epoch!==runtime.responseEpoch)return;salesman.chat.busy=false;setAvatarState('idle');salesman.chat.quick=defaultQuick();salesman.avatar.subtitle='這次回應未完成，請再試一次。';renderChat();toast('回應暫時無法完成，你可以再送出訊息。');}}

/* Editable ROI remains in the shared transcript, with unique IDs per surface. */
function renderROI(d,index=0,scope='main'){const saving=d.team*d.cost*d.rate/100,price=d.price,ratio=price>0?(saving/price).toFixed(1)+' 倍':'不適用';return `<div class="roi-card" data-roi-index="${index}"><span class="eyebrow">ROI 情境估算 · 非保證結果</span><div class="grid2" style="margin-top:13px"><div><label for="${scope}-roi-team-${index}">客服人數</label><input id="${scope}-roi-team-${index}" data-roi="team" data-message-index="${index}" type="number" min="1" max="10000" value="${d.team}"></div><div><label for="${scope}-roi-cost-${index}">每人月成本（美元）</label><input id="${scope}-roi-cost-${index}" data-roi="cost" data-message-index="${index}" type="number" min="1" max="100000" value="${d.cost}"></div></div><label for="${scope}-roi-rate-${index}" style="margin-top:11px">自動化比例（%）</label><input id="${scope}-roi-rate-${index}" data-roi="rate" data-message-index="${index}" type="number" min="0" max="100" value="${d.rate}"><div class="row between"><span>每月可釋放容量</span><strong data-roi-output="saving">${money(saving)}</strong></div><div class="row between"><span>產品月費</span><span>${price===null?'專屬報價':money(price)}</span></div><div class="row between"><span>價值／成本</span><strong data-roi-output="ratio">${ratio}</strong></div><p>假設：人數 × 每人月成本 × 自動化比例。淨 ROI：<span data-roi-output="net">${price>0?((saving-price)/price*100).toFixed(0)+'%':'不適用'}</span>。金額均以每月美元示範；尚未計入導入與維護成本，可釋放容量不等於現金節省。</p><button class="btn primary full roi-cta" data-quick="${esc(salesman.sales.cta)}">${esc(salesman.sales.cta)}</button></div>`;}
function updateROI(el){const index=Number(el.dataset.messageIndex),entry=salesman.chat.messages[index];if(!entry||entry.role!=='roi')return;const value=Number(el.value);if(el.value===''||!Number.isFinite(value))return;entry.data[el.dataset.roi]=Math.max(Number(el.getAttribute('min')),Math.min(Number(el.getAttribute('max')),value));const d=entry.data,s=d.team*d.cost*d.rate/100;$$('[data-roi-index="'+index+'"]').forEach(card=>{for(const key of ['team','cost','rate']){const input=card.querySelector('[data-roi="'+key+'"]');if(input!==el)input.value=d[key];}card.querySelector('[data-roi-output="saving"]').textContent=money(s);card.querySelector('[data-roi-output="ratio"]').textContent=d.price>0?(s/d.price).toFixed(1)+' 倍':'不適用';card.querySelector('[data-roi-output="net"]').textContent=d.price>0?((s-d.price)/d.price*100).toFixed(0)+'%':'不適用';});scheduleSave();}
/* Website embedding demonstration: isolated modal, shared conversation state. */
function openWebsitePreview(){UI_STATE.websiteOpen=true;renderWebsite();$('#website-modal').showModal();}
function closeWebsitePreview(){UI_STATE.websiteOpen=false;UI_STATE.websiteWidgetOpen=false;stopVoiceConversation({silent:true});$('#website-modal').close();renderPreviewMode();renderChat();}
function openWidget(){UI_STATE.websiteWidgetOpen=true;salesman.meta.previewMode=UI_STATE.websiteEntry;ensureConversation();renderPreviewMode();renderChat();scheduleSave();}
function closeWidget(){UI_STATE.websiteWidgetOpen=false;stopVoiceConversation({silent:true});renderPreviewMode();renderChat();}
function changePreviewMode(mode){if(!['avatar','chat'].includes(mode))return;salesman.meta.previewMode=mode;renderPreviewMode();renderChatPreview();scheduleSave();}
/* Local conversion forms: never send or store personal contact details. */
function openConversion(){const goal=salesman.sales.goal,booking=goal==='book_demo';$('#booking-content').innerHTML=`<span class="pill">模擬成交下一步</span><h2 id="booking-title">${esc(salesman.sales.cta||GOALS[goal])}</h2><p>${booking?'安排一場 20 分鐘、貼近你們需求的 Demo。':'完成一筆「'+esc(GOALS[goal])+'」示範請求。'}此表單不會送出真實請求。</p><form id="booking-form"><div class="field"><label for="lead-name">姓名 *</label><input id="lead-name" name="name" required autocomplete="name"></div><div class="field"><label for="lead-email">工作信箱 *</label><input id="lead-email" name="email" type="email" required autocomplete="email"></div>${booking?'<div class="grid2"><div class="field"><label for="lead-date">希望日期 *</label><input id="lead-date" name="date" type="date" required></div><div class="field"><label for="lead-time">時間（裝置時區）</label><select id="lead-time" name="time"><option>10:00</option><option>14:00</option><option>16:00</option></select></div></div>':''}<button class="btn primary full" style="margin-top:22px">${booking?'確認模擬預約':'完成示範請求'}</button><p class="inline-notice">Demo 不會寄信、建立行事曆事件、付款或聯絡外部服務。姓名及信箱不會被儲存。</p></form>`;if(booking){const date=new Date();date.setDate(date.getDate()+1);const local=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;$('#lead-date').setAttribute('min',local);$('#lead-date').value=local;}$('#booking-dialog').showModal();}
async function startDictation(targetId){if(targetId==='chat-input'){await startVoiceConversation();return;}if(runtime.recognition){abortRecognition();$('#describe-voice').innerHTML=icon('mic')+'用語音描述';return;}$('#describe-voice').textContent='● 正在聆聽…';try{const result=await speechToText();$('#description').value=result;salesman.description=result;scheduleSave();toast('已轉成文字，確認後按「產生設定」。');}catch(error){if(error.code!=='cancelled')toast('目前無法使用語音辨識，你可以直接輸入描述。');}finally{$('#describe-voice').innerHTML=icon('mic')+'用語音描述';salesman.avatar.transcript='';renderAvatarState();}}

/* Event listeners: mutate centralized state, then render only affected surfaces. */
document.addEventListener('input',event=>{const el=event.target;if(el.dataset.bind){const path=el.dataset.bind;const value=el.type==='range'?Number(el.value):el.dataset.array?el.value.split('\n').map(x=>x.trim()).filter(Boolean):el.value;pathSet(salesman,path,value);if(path==='description'){scheduleSave();return;}if(path==='appearance.age')$('#age-output').textContent=value;if(path.startsWith('personality.'))$('#out-'+path.split('.')[1]).textContent=value;if(path.startsWith('appearance.')&&path!=='appearance.image_description'){salesman.appearance.variant=bestVariant();renderVariants();}markChanged();}if(el.dataset.objection!==undefined){const item=salesman.objections[Number(el.dataset.objection)];if(item){item[el.dataset.key]=el.value;markChanged();}}if(el.dataset.roi)updateROI(el);});
document.addEventListener('change',event=>{const el=event.target;if(el.dataset.list){const values=pathGet(salesman,el.dataset.list);if(el.checked&&!values.includes(el.value))values.push(el.value);else if(!el.checked){const index=values.indexOf(el.value);if(index>=0)values.splice(index,1);}markChanged();}if(el.name==='goal'){salesman.sales.goal=el.value;salesman.sales.cta=GOALS[el.value];salesman.chat.quick=salesman.chat.quick.map(q=>Object.values(GOALS).includes(q)?GOALS[el.value]:q);renderGoals();markChanged();}if(el.id==='file-upload'){mockUploadFiles(el.files);el.value='';}if(el.dataset.roi){el.value=String(Math.max(Number(el.getAttribute('min')),Math.min(Number(el.getAttribute('max')),Number(el.value)||Number(el.getAttribute('min')))));updateROI(el);}});
document.addEventListener('keydown',event=>{if(event.target.id==='benefit-input'&&event.key==='Enter'){event.preventDefault();const value=event.target.value.trim();if(value&&!salesman.product.benefits.includes(value)){salesman.product.benefits.push(value);renderBenefits();$('#benefit-input').focus();markChanged();}}if(event.target.matches('[role="tab"]')&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();const tabs=$$('[role="tab"]'),index=(tabs.indexOf(event.target)+(event.key==='ArrowRight'?1:tabs.length-1))%tabs.length;tabs[index].click();tabs[index].focus();}});
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;const d=button.dataset;
 if(d.close){$('#'+d.close).close();return;}
 if(d.previewMode){changePreviewMode(d.previewMode);return;}
 if(d.startVoice!==undefined){await startVoiceConversation();return;}
 if(d.endVoice!==undefined){stopVoiceConversation();return;}
 if(d.quick){await sendMessage(d.quick);return;}
 if(d.persona){applyPreset(d.persona);renderAll();persist();toast('已切換為 '+PRESETS[d.persona].zh+'。產品訓練內容已保留。');return;}
 if(d.variant!==undefined){const selected=Number(d.variant),v=VARIANT_META[salesman.preset][selected];salesman.appearance={...salesman.appearance,...Object.fromEntries(Object.entries(v).filter(([k])=>k!=='label')),variant:selected};renderSettings();markChanged();toast('已套用形象變體：'+v.label);return;}
 if(d.example){salesman.description=EXAMPLES[d.example];$('#description').value=salesman.description;$('#description').focus();scheduleSave();return;}
 if(d.tab){$$('[data-tab]').forEach(b=>{const selected=b===button;b.classList.toggle('active',selected);b.setAttribute('aria-selected',selected);b.tabIndex=selected?0:-1;$('#panel-'+b.dataset.tab).hidden=!selected;});return;}
 if(d.device){salesman.meta.device=d.device;renderWebsite();scheduleSave();return;}
 if(d.websiteEntry){UI_STATE.websiteEntry=d.websiteEntry;if(UI_STATE.websiteWidgetOpen)changePreviewMode(d.websiteEntry);renderWebsite();return;}
 if(d.plan){salesman.chat.plan=d.plan;renderWebsite();UI_STATE.websiteEntry='chat';openWidget();if(!salesman.chat.messages.length)ensureConversation();await sendMessage('比較方案');return;}
 if(d.nav){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===d.nav));if(d.nav==='Conversations'){changePreviewMode('chat');$('#live-preview').scrollIntoView({behavior:'smooth',block:'nearest'});return;}const targets={Salesmen:'create-section',Knowledge:'knowledge-section',Playbooks:'objection-section',Settings:'personality-details'};if(targets[d.nav]){const target=$('#'+targets[d.nav]);if(target.tagName==='DETAILS')target.open=true;target.scrollIntoView({behavior:'smooth',block:'start'});}else toast(button.textContent.trim()+' 是此 Demo 的導覽示意，尚未串接資料。');return;}
 if(d.removeBenefit!==undefined){salesman.product.benefits.splice(Number(d.removeBenefit),1);renderBenefits();markChanged();return;}
 if(d.removeFile!==undefined){salesman.knowledge.files.splice(Number(d.removeFile),1);renderImports();markChanged();return;}
 if(d.removeObjection!==undefined){salesman.objections.splice(Number(d.removeObjection),1);renderObjections();markChanged();return;}
 switch(button.id){
 case 'generate-settings':if(!salesman.description.trim()){toast('先告訴我們，你想要一位什麼樣的業務員。');$('#description').focus();break;}button.disabled=true;button.textContent='正在理解你的描述…';await sleep(650);try{const key=parseDescription(salesman.description);salesman.appearance.variant=bestVariant();salesman.avatar.subtitle=openingLine();renderAll();persist();$('#parse-feedback').textContent='✓ 已選擇 '+PRESETS[key].zh+'，並更新外型、人格、聲音與銷售方式。';toast('設定已更新。準備好後，按「建立 AI Salesman」完成訓練。');}finally{button.disabled=false;button.innerHTML=icon('spark')+'產生設定';}break;
 case 'generate-appearance':stopVoiceConversation({silent:true});if(await mockLoading(['正在分析外型設定…','正在比對人格與能量…','正在搭配服裝與環境…','正在準備真人形象…'],'為你的業務找到合適形象。')){const previous=salesman.appearance.variant;mockGenerateImage();renderVariants();markChanged();toast(previous===salesman.appearance.variant?'目前形象已是最接近的變體；也可直接選取另一款形象。':'已換成更接近設定的形象變體。');}break;
 case 'preview-voice':clearTimeout(runtime.voicePreviewTimer);$('#waveform').classList.add('playing');button.textContent='正在預覽 '+salesman.voice.name;runtime.voicePreviewTimer=setTimeout(()=>{$('#waveform').classList.remove('playing');button.textContent='▷ 預覽聲音';},3000);break;
 case 'generate-salesman':await generateSalesman();break;
 case 'import-website':await mockImportWebsite();break;
 case 'add-objection':salesman.objections.push({objection:'如果不適合我們的團隊呢？',strategy:'用客戶實際工作流程安排驗證，確認是否符合需求。',never:'在沒有證據前保證效果。',response_style:'誠實、清楚、讓人安心。'});renderObjections();markChanged();$('#objection-list').lastElementChild.scrollIntoView({behavior:'smooth',block:'nearest'});break;
 case 'save-draft':clearTimeout(saveTimer);toast(persist()?'草稿已儲存在這個裝置。':'瀏覽器無法儲存。你仍可匯出業務檔案保留設定。');break;
 case 'preview-website':openWebsitePreview();break;
 case 'close-website':closeWebsitePreview();break;
 case 'website-launcher':openWidget();break;
 case 'close-website-widget':closeWidget();break;
 case 'show-profile':case 'website-show-profile':renderProfileDrawer();$('#profile-drawer').showModal();break;
 case 'copy-embed':{const code='<script src="ai-salesman.js" data-salesman="alex"></'+'script>';try{if(!navigator.clipboard?.writeText)throw Error();await navigator.clipboard.writeText(code);toast('已複製示意嵌入碼；尚未提供可用的嵌入服務。');}catch{info('複製示意嵌入碼',`<p>瀏覽器未允許直接複製，請選取下方文字複製。</p><textarea readonly aria-label="示意嵌入碼">${esc(code)}</textarea><p>此程式碼僅為概念示意，尚無實際嵌入服務。</p>`);}break;}
 case 'publish':info('準備讓你的業務上線',`<p>${esc(salesman.identity.name)} 目前狀態：${trainingStatus()}。</p><div class="import-result">✓ 真人與文字模式可在本機體驗<br>✓ 支援網站入口示範<br>○ 發布及外部網站部署尚未串接</div><p>按「預覽網站」即可完整展示訪客體驗。此操作不會發布網站。</p>`);break;
 case 'new-salesman':case 'reset-demo':$('#reset-dialog').showModal();break;
 case 'confirm-reset':stopVoiceConversation({silent:true});clearTimeout(saveTimer);clearTimeout(runtime.voicePreviewTimer);salesman=defaultState();UI_STATE.websiteWidgetOpen=false;UI_STATE.fallbackOpen=false;try{localStorage.removeItem(STORAGE_KEY);}catch{}$('#reset-dialog').close();renderAll();persist();window.scrollTo({top:0,behavior:'smooth'});toast('已重設 Demo。Alex 以草稿狀態準備開始。');break;
 case 'export-profile':{const profile=buildOutputContract();profile.preview={mode:salesman.meta.previewMode,avatar:{state:salesman.avatar.state},generation_status:salesman.meta.generated?'trained':'draft',readiness:readinessScore()};profile.conversation.messages=clone(salesman.chat.messages);profile.conversation.stage=salesman.chat.stage;const blob=new Blob([JSON.stringify(profile,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ai-salesman-profile-v2.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已匯出設定、銷售策略及共用對話紀錄。');break;}
 case 'describe-voice':await startDictation('description');break;
 case 'image-credits':info('關於這個 AI Salesman Demo','<p>人物為原創虛構角色，六種人格各有兩個預先製作的影像變體；素材由內建影像生成工具製作，已內嵌於本機檔案。</p><p>人物動態使用輕微呼吸、鏡頭位移與說話時的波形模擬，並非真正嘴型同步或即時人物影片。配音目前只有字幕演示，不會播放聲音。</p><p>可選的瀏覽器語音辨識使用 Web Speech API；依瀏覽器實作，音訊可能由瀏覽器供應商的服務處理。產品匯入、對話、ROI 與預約皆為前端模擬。</p>');break;
 }
});
document.addEventListener('submit',async event=>{const form=event.target;if(form.dataset.chatForm||form.dataset.voiceForm){event.preventDefault();const scope=form.dataset.chatForm||form.dataset.voiceForm;const input=form.querySelector('input');if(input.value.trim()){UI_STATE.fallbackOpen=false;await sendMessage(input.value);}return;}if(form.id!=='booking-form')return;event.preventDefault();const data=new FormData(form),name=String(data.get('name')||'').trim(),date=data.get('date'),time=data.get('time');$('#booking-content').innerHTML=`<div class="booking-confirm"><div class="big-check">✓</div><h2 id="booking-title">示範請求已完成</h2><p>${esc(name)}，你的「${esc(GOALS[salesman.sales.goal])}」模擬請求已準備好。${date?'<br>'+esc(date)+' '+esc(time)+'（裝置時區）':''}</p><span class="pill">僅供示範 · 未送出任何請求</span><p>沒有建立預約或寄送郵件，也沒有儲存你的姓名與信箱。未來可在此串接 CRM 或預約服務。</p><button class="btn primary full" data-close="booking-dialog">返回對話</button></div>`;salesman.chat.messages.push({role:'assistant',speaker:firstName(),text:'你的模擬下一步已完成。這次沒有建立真實預約或外部請求。謝謝你體驗 Demo。'});salesman.chat.quick=['比較方案','看看就好'];salesman.avatar.subtitle='示範請求已完成。期待再次與你對話。';renderChat();persist();});
const dropzone=$('#dropzone');['dragenter','dragover'].forEach(type=>dropzone.addEventListener(type,event=>{event.preventDefault();dropzone.classList.add('dragging');}));['dragleave','drop'].forEach(type=>dropzone.addEventListener(type,event=>{event.preventDefault();dropzone.classList.remove('dragging');}));dropzone.addEventListener('drop',event=>mockUploadFiles(event.dataTransfer.files));
$('#loading-dialog').addEventListener('cancel',event=>event.preventDefault());$('#website-modal').addEventListener('cancel',event=>{event.preventDefault();closeWebsitePreview();});$('#website-modal').addEventListener('close',()=>{UI_STATE.websiteOpen=false;UI_STATE.websiteWidgetOpen=false;});
window.addEventListener('pagehide',()=>{stopVoiceConversation({silent:true});persist();});
renderAll();if(!storageAvailable)toast('此瀏覽器無法儲存設定，但你仍可使用 Demo 並匯出檔案。');

